// Package cairn.v1 contains the public API surface of Cairn.
//
// All RPCs are exposed simultaneously as gRPC, gRPC-Web, and Connect-JSON
// from a single Connect-Go handler. The same .proto files generate
// OpenAPI v3 for REST/HTTP consumers and Connect-Web clients for the
// SvelteKit frontend.
//
// Convention: IDs are UUID strings (UUIDv7 for time-ordered insertion).
// Timestamps use google.protobuf.Timestamp (RFC 3339).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cairn/v1/common.proto

package cairnv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorClass int32

const (
	ErrorClass_ERROR_CLASS_UNSPECIFIED ErrorClass = 0
	// The requested resource does not exist.
	ErrorClass_ERROR_CLASS_NOT_FOUND ErrorClass = 1
	// The caller is authenticated but lacks permission for the resource.
	ErrorClass_ERROR_CLASS_PERMISSION_DENIED ErrorClass = 2
	// Input failed business-rule validation.
	// Details carry per-field error messages.
	ErrorClass_ERROR_CLASS_VALIDATION ErrorClass = 3
	// The operation would conflict with current state (e.g. unique constraint).
	ErrorClass_ERROR_CLASS_CONFLICT ErrorClass = 4
	// The caller has hit a rate limit. retry_after_ms carries the suggested wait.
	ErrorClass_ERROR_CLASS_RATE_LIMITED ErrorClass = 5
	// An upstream dependency (provider API, worker, queue) is unavailable.
	ErrorClass_ERROR_CLASS_DEPENDENCY_UNAVAILABLE ErrorClass = 6
	// Internal server error — no useful information for the client.
	ErrorClass_ERROR_CLASS_INTERNAL ErrorClass = 7
)

// Enum value maps for ErrorClass.
var (
	ErrorClass_name = map[int32]string{
		0: "ERROR_CLASS_UNSPECIFIED",
		1: "ERROR_CLASS_NOT_FOUND",
		2: "ERROR_CLASS_PERMISSION_DENIED",
		3: "ERROR_CLASS_VALIDATION",
		4: "ERROR_CLASS_CONFLICT",
		5: "ERROR_CLASS_RATE_LIMITED",
		6: "ERROR_CLASS_DEPENDENCY_UNAVAILABLE",
		7: "ERROR_CLASS_INTERNAL",
	}
	ErrorClass_value = map[string]int32{
		"ERROR_CLASS_UNSPECIFIED":            0,
		"ERROR_CLASS_NOT_FOUND":              1,
		"ERROR_CLASS_PERMISSION_DENIED":      2,
		"ERROR_CLASS_VALIDATION":             3,
		"ERROR_CLASS_CONFLICT":               4,
		"ERROR_CLASS_RATE_LIMITED":           5,
		"ERROR_CLASS_DEPENDENCY_UNAVAILABLE": 6,
		"ERROR_CLASS_INTERNAL":               7,
	}
)

func (x ErrorClass) Enum() *ErrorClass {
	p := new(ErrorClass)
	*p = x
	return p
}

func (x ErrorClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorClass) Descriptor() protoreflect.EnumDescriptor {
	return file_cairn_v1_common_proto_enumTypes[0].Descriptor()
}

func (ErrorClass) Type() protoreflect.EnumType {
	return &file_cairn_v1_common_proto_enumTypes[0]
}

func (x ErrorClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorClass.Descriptor instead.
func (ErrorClass) EnumDescriptor() ([]byte, []int) {
	return file_cairn_v1_common_proto_rawDescGZIP(), []int{0}
}

type PageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque cursor from a previous PageResponse.next_cursor.
	// Empty for the first page.
	Cursor string `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	// Max items to return. Server caps at an endpoint-specific maximum
	// (typically 100). Zero means "use server default".
	Limit         int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageRequest) Reset() {
	*x = PageRequest{}
	mi := &file_cairn_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRequest) ProtoMessage() {}

func (x *PageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRequest.ProtoReflect.Descriptor instead.
func (*PageRequest) Descriptor() ([]byte, []int) {
	return file_cairn_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *PageRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *PageRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type PageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Cursor for the next page. Empty when no more pages remain.
	NextCursor string `protobuf:"bytes,1,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	// Total count if cheap to compute, otherwise -1.
	// Clients should not rely on this being populated for every endpoint.
	Total         int64 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageResponse) Reset() {
	*x = PageResponse{}
	mi := &file_cairn_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageResponse) ProtoMessage() {}

func (x *PageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageResponse.ProtoReflect.Descriptor instead.
func (*PageResponse) Descriptor() ([]byte, []int) {
	return file_cairn_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *PageResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *PageResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type TimeRange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Inclusive lower bound. If unset, treated as -infinity.
	From *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	// Exclusive upper bound. If unset, treated as +infinity.
	To            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeRange) Reset() {
	*x = TimeRange{}
	mi := &file_cairn_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRange) ProtoMessage() {}

func (x *TimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRange.ProtoReflect.Descriptor instead.
func (*TimeRange) Descriptor() ([]byte, []int) {
	return file_cairn_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *TimeRange) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *TimeRange) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

// Returned in error details for richer client-side handling.
type ErrorDetail struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Class ErrorClass             `protobuf:"varint,1,opt,name=class,proto3,enum=cairn.v1.ErrorClass" json:"class,omitempty"`
	// Machine-readable error code, e.g. "activity.duplicate",
	// "external_account.auth_expired". Stable across versions.
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// i18n key for client-side localization, e.g.
	// "errors.external_account.auth_expired".
	// The frontend resolves this with Paraglide; metadata supplies template vars.
	I18NKey    string            `protobuf:"bytes,3,opt,name=i18n_key,json=i18nKey,proto3" json:"i18n_key,omitempty"`
	I18NParams map[string]string `protobuf:"bytes,4,rep,name=i18n_params,json=i18nParams,proto3" json:"i18n_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Suggested retry-after in milliseconds. Zero means no suggestion.
	// Populated for RATE_LIMITED and some DEPENDENCY_UNAVAILABLE errors.
	RetryAfterMs int64 `protobuf:"varint,5,opt,name=retry_after_ms,json=retryAfterMs,proto3" json:"retry_after_ms,omitempty"`
	// Optional per-field validation messages (path -> message).
	// Populated for ERROR_CLASS_VALIDATION.
	FieldErrors   map[string]string `protobuf:"bytes,6,rep,name=field_errors,json=fieldErrors,proto3" json:"field_errors,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_cairn_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_cairn_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *ErrorDetail) GetClass() ErrorClass {
	if x != nil {
		return x.Class
	}
	return ErrorClass_ERROR_CLASS_UNSPECIFIED
}

func (x *ErrorDetail) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorDetail) GetI18NKey() string {
	if x != nil {
		return x.I18NKey
	}
	return ""
}

func (x *ErrorDetail) GetI18NParams() map[string]string {
	if x != nil {
		return x.I18NParams
	}
	return nil
}

func (x *ErrorDetail) GetRetryAfterMs() int64 {
	if x != nil {
		return x.RetryAfterMs
	}
	return 0
}

func (x *ErrorDetail) GetFieldErrors() map[string]string {
	if x != nil {
		return x.FieldErrors
	}
	return nil
}

// Convention marker; do not embed in messages — fields use plain `string`
// with this name to aid static search.
type ProviderIdConventionMarker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderIdConventionMarker) Reset() {
	*x = ProviderIdConventionMarker{}
	mi := &file_cairn_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderIdConventionMarker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderIdConventionMarker) ProtoMessage() {}

func (x *ProviderIdConventionMarker) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderIdConventionMarker.ProtoReflect.Descriptor instead.
func (*ProviderIdConventionMarker) Descriptor() ([]byte, []int) {
	return file_cairn_v1_common_proto_rawDescGZIP(), []int{4}
}

// A geographic point. Latitude/Longitude in WGS84.
type GeoPoint struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Latitude  float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	// Elevation in meters. Optional.
	ElevationM    *float64 `protobuf:"fixed64,3,opt,name=elevation_m,json=elevationM,proto3,oneof" json:"elevation_m,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoPoint) Reset() {
	*x = GeoPoint{}
	mi := &file_cairn_v1_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoPoint) ProtoMessage() {}

func (x *GeoPoint) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_v1_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoPoint.ProtoReflect.Descriptor instead.
func (*GeoPoint) Descriptor() ([]byte, []int) {
	return file_cairn_v1_common_proto_rawDescGZIP(), []int{5}
}

func (x *GeoPoint) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GeoPoint) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GeoPoint) GetElevationM() float64 {
	if x != nil && x.ElevationM != nil {
		return *x.ElevationM
	}
	return 0
}

// A polyline encoded as Google's encoded polyline algorithm (precision 5 or 6).
// PostGIS GEOGRAPHY values are converted to/from this on the API boundary.
type EncodedPolyline struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Encoded string                 `protobuf:"bytes,1,opt,name=encoded,proto3" json:"encoded,omitempty"`
	// 5 for Strava-style, 6 for higher precision.
	Precision     int32 `protobuf:"varint,2,opt,name=precision,proto3" json:"precision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncodedPolyline) Reset() {
	*x = EncodedPolyline{}
	mi := &file_cairn_v1_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncodedPolyline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodedPolyline) ProtoMessage() {}

func (x *EncodedPolyline) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_v1_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodedPolyline.ProtoReflect.Descriptor instead.
func (*EncodedPolyline) Descriptor() ([]byte, []int) {
	return file_cairn_v1_common_proto_rawDescGZIP(), []int{6}
}

func (x *EncodedPolyline) GetEncoded() string {
	if x != nil {
		return x.Encoded
	}
	return ""
}

func (x *EncodedPolyline) GetPrecision() int32 {
	if x != nil {
		return x.Precision
	}
	return 0
}

// A bounding box for spatial queries.
type BoundingBox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinLatitude   float64                `protobuf:"fixed64,1,opt,name=min_latitude,json=minLatitude,proto3" json:"min_latitude,omitempty"`
	MinLongitude  float64                `protobuf:"fixed64,2,opt,name=min_longitude,json=minLongitude,proto3" json:"min_longitude,omitempty"`
	MaxLatitude   float64                `protobuf:"fixed64,3,opt,name=max_latitude,json=maxLatitude,proto3" json:"max_latitude,omitempty"`
	MaxLongitude  float64                `protobuf:"fixed64,4,opt,name=max_longitude,json=maxLongitude,proto3" json:"max_longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoundingBox) Reset() {
	*x = BoundingBox{}
	mi := &file_cairn_v1_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoundingBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundingBox) ProtoMessage() {}

func (x *BoundingBox) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_v1_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundingBox.ProtoReflect.Descriptor instead.
func (*BoundingBox) Descriptor() ([]byte, []int) {
	return file_cairn_v1_common_proto_rawDescGZIP(), []int{7}
}

func (x *BoundingBox) GetMinLatitude() float64 {
	if x != nil {
		return x.MinLatitude
	}
	return 0
}

func (x *BoundingBox) GetMinLongitude() float64 {
	if x != nil {
		return x.MinLongitude
	}
	return 0
}

func (x *BoundingBox) GetMaxLatitude() float64 {
	if x != nil {
		return x.MaxLatitude
	}
	return 0
}

func (x *BoundingBox) GetMaxLongitude() float64 {
	if x != nil {
		return x.MaxLongitude
	}
	return 0
}

var File_cairn_v1_common_proto protoreflect.FileDescriptor

const file_cairn_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x15cairn/v1/common.proto\x12\bcairn.v1\x1a\x1fgoogle/protobuf/timestamp.proto\";\n" +
	"\vPageRequest\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"E\n" +
	"\fPageResponse\x12\x1f\n" +
	"\vnext_cursor\x18\x01 \x01(\tR\n" +
	"nextCursor\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"g\n" +
	"\tTimeRange\x12.\n" +
	"\x04from\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\"\xa0\x03\n" +
	"\vErrorDetail\x12*\n" +
	"\x05class\x18\x01 \x01(\x0e2\x14.cairn.v1.ErrorClassR\x05class\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x19\n" +
	"\bi18n_key\x18\x03 \x01(\tR\ai18nKey\x12F\n" +
	"\vi18n_params\x18\x04 \x03(\v2%.cairn.v1.ErrorDetail.I18nParamsEntryR\n" +
	"i18nParams\x12$\n" +
	"\x0eretry_after_ms\x18\x05 \x01(\x03R\fretryAfterMs\x12I\n" +
	"\ffield_errors\x18\x06 \x03(\v2&.cairn.v1.ErrorDetail.FieldErrorsEntryR\vfieldErrors\x1a=\n" +
	"\x0fI18nParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10FieldErrorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\" \n" +
	"\x1aProviderIdConventionMarker:\x02\x18\x00\"z\n" +
	"\bGeoPoint\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12$\n" +
	"\velevation_m\x18\x03 \x01(\x01H\x00R\n" +
	"elevationM\x88\x01\x01B\x0e\n" +
	"\f_elevation_m\"I\n" +
	"\x0fEncodedPolyline\x12\x18\n" +
	"\aencoded\x18\x01 \x01(\tR\aencoded\x12\x1c\n" +
	"\tprecision\x18\x02 \x01(\x05R\tprecision\"\x9d\x01\n" +
	"\vBoundingBox\x12!\n" +
	"\fmin_latitude\x18\x01 \x01(\x01R\vminLatitude\x12#\n" +
	"\rmin_longitude\x18\x02 \x01(\x01R\fminLongitude\x12!\n" +
	"\fmax_latitude\x18\x03 \x01(\x01R\vmaxLatitude\x12#\n" +
	"\rmax_longitude\x18\x04 \x01(\x01R\fmaxLongitude*\xfd\x01\n" +
	"\n" +
	"ErrorClass\x12\x1b\n" +
	"\x17ERROR_CLASS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ERROR_CLASS_NOT_FOUND\x10\x01\x12!\n" +
	"\x1dERROR_CLASS_PERMISSION_DENIED\x10\x02\x12\x1a\n" +
	"\x16ERROR_CLASS_VALIDATION\x10\x03\x12\x18\n" +
	"\x14ERROR_CLASS_CONFLICT\x10\x04\x12\x1c\n" +
	"\x18ERROR_CLASS_RATE_LIMITED\x10\x05\x12&\n" +
	"\"ERROR_CLASS_DEPENDENCY_UNAVAILABLE\x10\x06\x12\x18\n" +
	"\x14ERROR_CLASS_INTERNAL\x10\aB\x99\x01\n" +
	"\fcom.cairn.v1B\vCommonProtoP\x01Z;github.com/johnnycube/cairn-core/gen/proto/cairn/v1;cairnv1\xa2\x02\x03CXX\xaa\x02\bCairn.V1\xca\x02\bCairn\\V1\xe2\x02\x14Cairn\\V1\\GPBMetadata\xea\x02\tCairn::V1b\x06proto3"

var (
	file_cairn_v1_common_proto_rawDescOnce sync.Once
	file_cairn_v1_common_proto_rawDescData []byte
)

func file_cairn_v1_common_proto_rawDescGZIP() []byte {
	file_cairn_v1_common_proto_rawDescOnce.Do(func() {
		file_cairn_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cairn_v1_common_proto_rawDesc), len(file_cairn_v1_common_proto_rawDesc)))
	})
	return file_cairn_v1_common_proto_rawDescData
}

var file_cairn_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cairn_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_cairn_v1_common_proto_goTypes = []any{
	(ErrorClass)(0),                    // 0: cairn.v1.ErrorClass
	(*PageRequest)(nil),                // 1: cairn.v1.PageRequest
	(*PageResponse)(nil),               // 2: cairn.v1.PageResponse
	(*TimeRange)(nil),                  // 3: cairn.v1.TimeRange
	(*ErrorDetail)(nil),                // 4: cairn.v1.ErrorDetail
	(*ProviderIdConventionMarker)(nil), // 5: cairn.v1.ProviderIdConventionMarker
	(*GeoPoint)(nil),                   // 6: cairn.v1.GeoPoint
	(*EncodedPolyline)(nil),            // 7: cairn.v1.EncodedPolyline
	(*BoundingBox)(nil),                // 8: cairn.v1.BoundingBox
	nil,                                // 9: cairn.v1.ErrorDetail.I18nParamsEntry
	nil,                                // 10: cairn.v1.ErrorDetail.FieldErrorsEntry
	(*timestamppb.Timestamp)(nil),      // 11: google.protobuf.Timestamp
}
var file_cairn_v1_common_proto_depIdxs = []int32{
	11, // 0: cairn.v1.TimeRange.from:type_name -> google.protobuf.Timestamp
	11, // 1: cairn.v1.TimeRange.to:type_name -> google.protobuf.Timestamp
	0,  // 2: cairn.v1.ErrorDetail.class:type_name -> cairn.v1.ErrorClass
	9,  // 3: cairn.v1.ErrorDetail.i18n_params:type_name -> cairn.v1.ErrorDetail.I18nParamsEntry
	10, // 4: cairn.v1.ErrorDetail.field_errors:type_name -> cairn.v1.ErrorDetail.FieldErrorsEntry
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_cairn_v1_common_proto_init() }
func file_cairn_v1_common_proto_init() {
	if File_cairn_v1_common_proto != nil {
		return
	}
	file_cairn_v1_common_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cairn_v1_common_proto_rawDesc), len(file_cairn_v1_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cairn_v1_common_proto_goTypes,
		DependencyIndexes: file_cairn_v1_common_proto_depIdxs,
		EnumInfos:         file_cairn_v1_common_proto_enumTypes,
		MessageInfos:      file_cairn_v1_common_proto_msgTypes,
	}.Build()
	File_cairn_v1_common_proto = out.File
	file_cairn_v1_common_proto_goTypes = nil
	file_cairn_v1_common_proto_depIdxs = nil
}
