// Segments and segment efforts.
//
// A Segment is a named geographic path with a polyline. Cairn supports two
// sources:
//
//   * "strava" — mirrored read-only when activities are imported from
//     Strava. Each user holds their own copy (Strava's API binds segments
//     to the authenticated athlete). If two users on the same instance
//     star the same Strava segment, each has their own mirror.
//
//   * "cairn" — user-defined within Cairn. May be private (owner-only) or
//     shared instance-wide (any user on the instance can match efforts
//     against it). The owning user controls visibility.
//
// Segment matching runs on every activity import — irrespective of the
// activity's source — using PostGIS ST_DWithin to filter candidates and a
// Hausdorff-distance + direction check to confirm matches. Matched
// efforts are recorded in segment_efforts and trigger PR notifications
// when they beat the user's prior best.
//
// Records (fastest 5k, max 5min power, etc.) are NOT segment-scoped;
// see best efforts in activity.proto. Segment leaderboards are an
// instance-wide ranking of efforts against a shared segment.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cairn/v1/segment.proto

package cairnv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SegmentScope int32

const (
	SegmentScope_SEGMENT_SCOPE_UNSPECIFIED SegmentScope = 0
	SegmentScope_SEGMENT_SCOPE_PRIVATE     SegmentScope = 1 // visible only to owner_user_id
	SegmentScope_SEGMENT_SCOPE_INSTANCE    SegmentScope = 2 // visible to all users on the instance
)

// Enum value maps for SegmentScope.
var (
	SegmentScope_name = map[int32]string{
		0: "SEGMENT_SCOPE_UNSPECIFIED",
		1: "SEGMENT_SCOPE_PRIVATE",
		2: "SEGMENT_SCOPE_INSTANCE",
	}
	SegmentScope_value = map[string]int32{
		"SEGMENT_SCOPE_UNSPECIFIED": 0,
		"SEGMENT_SCOPE_PRIVATE":     1,
		"SEGMENT_SCOPE_INSTANCE":    2,
	}
)

func (x SegmentScope) Enum() *SegmentScope {
	p := new(SegmentScope)
	*p = x
	return p
}

func (x SegmentScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SegmentScope) Descriptor() protoreflect.EnumDescriptor {
	return file_cairn_v1_segment_proto_enumTypes[0].Descriptor()
}

func (SegmentScope) Type() protoreflect.EnumType {
	return &file_cairn_v1_segment_proto_enumTypes[0]
}

func (x SegmentScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SegmentScope.Descriptor instead.
func (SegmentScope) EnumDescriptor() ([]byte, []int) {
	return file_cairn_v1_segment_proto_rawDescGZIP(), []int{0}
}

type ClimbCategory int32

const (
	ClimbCategory_CLIMB_CATEGORY_UNSPECIFIED    ClimbCategory = 0
	ClimbCategory_CLIMB_CATEGORY_NONE           ClimbCategory = 1
	ClimbCategory_CLIMB_CATEGORY_FOUR           ClimbCategory = 2
	ClimbCategory_CLIMB_CATEGORY_THREE          ClimbCategory = 3
	ClimbCategory_CLIMB_CATEGORY_TWO            ClimbCategory = 4
	ClimbCategory_CLIMB_CATEGORY_ONE            ClimbCategory = 5
	ClimbCategory_CLIMB_CATEGORY_HORS_CATEGORIE ClimbCategory = 6
)

// Enum value maps for ClimbCategory.
var (
	ClimbCategory_name = map[int32]string{
		0: "CLIMB_CATEGORY_UNSPECIFIED",
		1: "CLIMB_CATEGORY_NONE",
		2: "CLIMB_CATEGORY_FOUR",
		3: "CLIMB_CATEGORY_THREE",
		4: "CLIMB_CATEGORY_TWO",
		5: "CLIMB_CATEGORY_ONE",
		6: "CLIMB_CATEGORY_HORS_CATEGORIE",
	}
	ClimbCategory_value = map[string]int32{
		"CLIMB_CATEGORY_UNSPECIFIED":    0,
		"CLIMB_CATEGORY_NONE":           1,
		"CLIMB_CATEGORY_FOUR":           2,
		"CLIMB_CATEGORY_THREE":          3,
		"CLIMB_CATEGORY_TWO":            4,
		"CLIMB_CATEGORY_ONE":            5,
		"CLIMB_CATEGORY_HORS_CATEGORIE": 6,
	}
)

func (x ClimbCategory) Enum() *ClimbCategory {
	p := new(ClimbCategory)
	*p = x
	return p
}

func (x ClimbCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClimbCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_cairn_v1_segment_proto_enumTypes[1].Descriptor()
}

func (ClimbCategory) Type() protoreflect.EnumType {
	return &file_cairn_v1_segment_proto_enumTypes[1]
}

func (x ClimbCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClimbCategory.Descriptor instead.
func (ClimbCategory) EnumDescriptor() ([]byte, []int) {
	return file_cairn_v1_segment_proto_rawDescGZIP(), []int{1}
}

type SegmentSort int32

const (
	SegmentSort_SEGMENT_SORT_UNSPECIFIED       SegmentSort = 0
	SegmentSort_SEGMENT_SORT_NAME_ASC          SegmentSort = 1
	SegmentSort_SEGMENT_SORT_DISTANCE_DESC     SegmentSort = 2
	SegmentSort_SEGMENT_SORT_ELEVATION_DESC    SegmentSort = 3
	SegmentSort_SEGMENT_SORT_EFFORT_COUNT_DESC SegmentSort = 4
	SegmentSort_SEGMENT_SORT_CREATED_AT_DESC   SegmentSort = 5
)

// Enum value maps for SegmentSort.
var (
	SegmentSort_name = map[int32]string{
		0: "SEGMENT_SORT_UNSPECIFIED",
		1: "SEGMENT_SORT_NAME_ASC",
		2: "SEGMENT_SORT_DISTANCE_DESC",
		3: "SEGMENT_SORT_ELEVATION_DESC",
		4: "SEGMENT_SORT_EFFORT_COUNT_DESC",
		5: "SEGMENT_SORT_CREATED_AT_DESC",
	}
	SegmentSort_value = map[string]int32{
		"SEGMENT_SORT_UNSPECIFIED":       0,
		"SEGMENT_SORT_NAME_ASC":          1,
		"SEGMENT_SORT_DISTANCE_DESC":     2,
		"SEGMENT_SORT_ELEVATION_DESC":    3,
		"SEGMENT_SORT_EFFORT_COUNT_DESC": 4,
		"SEGMENT_SORT_CREATED_AT_DESC":   5,
	}
)

func (x SegmentSort) Enum() *SegmentSort {
	p := new(SegmentSort)
	*p = x
	return p
}

func (x SegmentSort) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SegmentSort) Descriptor() protoreflect.EnumDescriptor {
	return file_cairn_v1_segment_proto_enumTypes[2].Descriptor()
}

func (SegmentSort) Type() protoreflect.EnumType {
	return &file_cairn_v1_segment_proto_enumTypes[2]
}

func (x SegmentSort) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SegmentSort.Descriptor instead.
func (SegmentSort) EnumDescriptor() ([]byte, []int) {
	return file_cairn_v1_segment_proto_rawDescGZIP(), []int{2}
}

type SegmentEffortSort int32

const (
	SegmentEffortSort_SEGMENT_EFFORT_SORT_UNSPECIFIED     SegmentEffortSort = 0
	SegmentEffortSort_SEGMENT_EFFORT_SORT_ELAPSED_ASC     SegmentEffortSort = 1 // fastest first
	SegmentEffortSort_SEGMENT_EFFORT_SORT_START_TIME_DESC SegmentEffortSort = 2 // recent first
)

// Enum value maps for SegmentEffortSort.
var (
	SegmentEffortSort_name = map[int32]string{
		0: "SEGMENT_EFFORT_SORT_UNSPECIFIED",
		1: "SEGMENT_EFFORT_SORT_ELAPSED_ASC",
		2: "SEGMENT_EFFORT_SORT_START_TIME_DESC",
	}
	SegmentEffortSort_value = map[string]int32{
		"SEGMENT_EFFORT_SORT_UNSPECIFIED":     0,
		"SEGMENT_EFFORT_SORT_ELAPSED_ASC":     1,
		"SEGMENT_EFFORT_SORT_START_TIME_DESC": 2,
	}
)

func (x SegmentEffortSort) Enum() *SegmentEffortSort {
	p := new(SegmentEffortSort)
	*p = x
	return p
}

func (x SegmentEffortSort) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SegmentEffortSort) Descriptor() protoreflect.EnumDescriptor {
	return file_cairn_v1_segment_proto_enumTypes[3].Descriptor()
}

func (SegmentEffortSort) Type() protoreflect.EnumType {
	return &file_cairn_v1_segment_proto_enumTypes[3]
}

func (x SegmentEffortSort) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SegmentEffortSort.Descriptor instead.
func (SegmentEffortSort) EnumDescriptor() ([]byte, []int) {
	return file_cairn_v1_segment_proto_rawDescGZIP(), []int{3}
}

type Segment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// "strava" (imported mirror) or "cairn" (user-defined).
	// Future: "komoot", "ridewithgps", etc. as importers materialize.
	Source string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	// Required for source="strava": the Strava segment id.
	// Empty for source="cairn".
	ExternalId *string `protobuf:"bytes,3,opt,name=external_id,json=externalId,proto3,oneof" json:"external_id,omitempty"`
	// Required for source="strava": the external_account whose Strava import
	// brought this in. The segment is only visible to that account's owner
	// (Strava terms-of-service compliance).
	ExternalAccountId *string `protobuf:"bytes,4,opt,name=external_account_id,json=externalAccountId,proto3,oneof" json:"external_account_id,omitempty"`
	// Required for source="cairn": the user who created the segment.
	OwnerUserId *string `protobuf:"bytes,5,opt,name=owner_user_id,json=ownerUserId,proto3,oneof" json:"owner_user_id,omitempty"`
	// Visibility scope. Strava-mirrored segments are always SEGMENT_SCOPE_PRIVATE
	// (one user). Cairn-native segments can be SCOPE_PRIVATE or SCOPE_INSTANCE.
	Scope       SegmentScope `protobuf:"varint,6,opt,name=scope,proto3,enum=cairn.v1.SegmentScope" json:"scope,omitempty"`
	Name        string       `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Description string       `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	// Type guidance — affects which activity types are eligible for matching.
	// RIDE-typed segments are matched against rides; RUN against runs, etc.
	// ACTIVITY_TYPE_WORKOUT acts as a wildcard (matched against all types).
	ActivityType ActivityType `protobuf:"varint,9,opt,name=activity_type,json=activityType,proto3,enum=cairn.v1.ActivityType" json:"activity_type,omitempty"`
	// Geometry — the path as an encoded polyline. The Core also stores a
	// PostGIS GEOGRAPHY column for spatial queries; this is the on-the-wire
	// form for clients.
	Polyline *EncodedPolyline `protobuf:"bytes,10,opt,name=polyline,proto3" json:"polyline,omitempty"`
	// Bounding box (denormalized for cheap filtering on map views).
	BoundingBox    *BoundingBox `protobuf:"bytes,11,opt,name=bounding_box,json=boundingBox,proto3" json:"bounding_box,omitempty"`
	DistanceM      float64      `protobuf:"fixed64,12,opt,name=distance_m,json=distanceM,proto3" json:"distance_m,omitempty"`
	ElevationGainM *float64     `protobuf:"fixed64,13,opt,name=elevation_gain_m,json=elevationGainM,proto3,oneof" json:"elevation_gain_m,omitempty"`
	ElevationLossM *float64     `protobuf:"fixed64,14,opt,name=elevation_loss_m,json=elevationLossM,proto3,oneof" json:"elevation_loss_m,omitempty"`
	MinElevationM  *float64     `protobuf:"fixed64,15,opt,name=min_elevation_m,json=minElevationM,proto3,oneof" json:"min_elevation_m,omitempty"`
	MaxElevationM  *float64     `protobuf:"fixed64,16,opt,name=max_elevation_m,json=maxElevationM,proto3,oneof" json:"max_elevation_m,omitempty"`
	AvgGrade       *float64     `protobuf:"fixed64,17,opt,name=avg_grade,json=avgGrade,proto3,oneof" json:"avg_grade,omitempty"`
	MaxGrade       *float64     `protobuf:"fixed64,18,opt,name=max_grade,json=maxGrade,proto3,oneof" json:"max_grade,omitempty"`
	// Climb categorization, if applicable (HC/1/2/3/4 for cycling, etc.).
	// Strava's classification is mirrored; Cairn computes for native segments.
	ClimbCategory *ClimbCategory `protobuf:"varint,19,opt,name=climb_category,json=climbCategory,proto3,enum=cairn.v1.ClimbCategory,oneof" json:"climb_category,omitempty"`
	// Matching tolerances. Set per-segment to handle wide variability (a
	// 30km route can afford a wider corridor than a 200m sprint).
	// Defaults come from server config if zero here.
	MatchCorridorM       *float64 `protobuf:"fixed64,20,opt,name=match_corridor_m,json=matchCorridorM,proto3,oneof" json:"match_corridor_m,omitempty"` // meters from polyline
	MatchStartToleranceM *float64 `protobuf:"fixed64,21,opt,name=match_start_tolerance_m,json=matchStartToleranceM,proto3,oneof" json:"match_start_tolerance_m,omitempty"`
	MatchEndToleranceM   *float64 `protobuf:"fixed64,22,opt,name=match_end_tolerance_m,json=matchEndToleranceM,proto3,oneof" json:"match_end_tolerance_m,omitempty"`
	// True means the segment can be matched in both directions
	// (otherwise direction is enforced).
	Bidirectional bool `protobuf:"varint,23,opt,name=bidirectional,proto3" json:"bidirectional,omitempty"`
	// Strava-only: a starred segment flag, mirrored from the user's account.
	Starred bool `protobuf:"varint,24,opt,name=starred,proto3" json:"starred,omitempty"`
	// Cached statistics — denormalized for fast list rendering.
	Stats         *SegmentStats          `protobuf:"bytes,25,opt,name=stats,proto3" json:"stats,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,26,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,27,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Segment) Reset() {
	*x = Segment{}
	mi := &file_cairn_v1_segment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Segment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Segment) ProtoMessage() {}

func (x *Segment) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_v1_segment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Segment.ProtoReflect.Descriptor instead.
func (*Segment) Descriptor() ([]byte, []int) {
	return file_cairn_v1_segment_proto_rawDescGZIP(), []int{0}
}

func (x *Segment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Segment) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Segment) GetExternalId() string {
	if x != nil && x.ExternalId != nil {
		return *x.ExternalId
	}
	return ""
}

func (x *Segment) GetExternalAccountId() string {
	if x != nil && x.ExternalAccountId != nil {
		return *x.ExternalAccountId
	}
	return ""
}

func (x *Segment) GetOwnerUserId() string {
	if x != nil && x.OwnerUserId != nil {
		return *x.OwnerUserId
	}
	return ""
}

func (x *Segment) GetScope() SegmentScope {
	if x != nil {
		return x.Scope
	}
	return SegmentScope_SEGMENT_SCOPE_UNSPECIFIED
}

func (x *Segment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Segment) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Segment) GetActivityType() ActivityType {
	if x != nil {
		return x.ActivityType
	}
	return ActivityType_ACTIVITY_TYPE_UNSPECIFIED
}

func (x *Segment) GetPolyline() *EncodedPolyline {
	if x != nil {
		return x.Polyline
	}
	return nil
}

func (x *Segment) GetBoundingBox() *BoundingBox {
	if x != nil {
		return x.BoundingBox
	}
	return nil
}

func (x *Segment) GetDistanceM() float64 {
	if x != nil {
		return x.DistanceM
	}
	return 0
}

func (x *Segment) GetElevationGainM() float64 {
	if x != nil && x.ElevationGainM != nil {
		return *x.ElevationGainM
	}
	return 0
}

func (x *Segment) GetElevationLossM() float64 {
	if x != nil && x.ElevationLossM != nil {
		return *x.ElevationLossM
	}
	return 0
}

func (x *Segment) GetMinElevationM() float64 {
	if x != nil && x.MinElevationM != nil {
		return *x.MinElevationM
	}
	return 0
}

func (x *Segment) GetMaxElevationM() float64 {
	if x != nil && x.MaxElevationM != nil {
		return *x.MaxElevationM
	}
	return 0
}

func (x *Segment) GetAvgGrade() float64 {
	if x != nil && x.AvgGrade != nil {
		return *x.AvgGrade
	}
	return 0
}

func (x *Segment) GetMaxGrade() float64 {
	if x != nil && x.MaxGrade != nil {
		return *x.MaxGrade
	}
	return 0
}

func (x *Segment) GetClimbCategory() ClimbCategory {
	if x != nil && x.ClimbCategory != nil {
		return *x.ClimbCategory
	}
	return ClimbCategory_CLIMB_CATEGORY_UNSPECIFIED
}

func (x *Segment) GetMatchCorridorM() float64 {
	if x != nil && x.MatchCorridorM != nil {
		return *x.MatchCorridorM
	}
	return 0
}

func (x *Segment) GetMatchStartToleranceM() float64 {
	if x != nil && x.MatchStartToleranceM != nil {
		return *x.MatchStartToleranceM
	}
	return 0
}

func (x *Segment) GetMatchEndToleranceM() float64 {
	if x != nil && x.MatchEndToleranceM != nil {
		return *x.MatchEndToleranceM
	}
	return 0
}

func (x *Segment) GetBidirectional() bool {
	if x != nil {
		return x.Bidirectional
	}
	return false
}

func (x *Segment) GetStarred() bool {
	if x != nil {
		return x.Starred
	}
	return false
}

func (x *Segment) GetStats() *SegmentStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *Segment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Segment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type SegmentStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total efforts recorded against this segment (cross-source).
	EffortCount int32 `protobuf:"varint,1,opt,name=effort_count,json=effortCount,proto3" json:"effort_count,omitempty"`
	// Distinct users who have an effort on this segment (instance segments).
	AthleteCount int32 `protobuf:"varint,2,opt,name=athlete_count,json=athleteCount,proto3" json:"athlete_count,omitempty"`
	// The current best effort time (any user, any source).
	KomTime     *durationpb.Duration `protobuf:"bytes,3,opt,name=kom_time,json=komTime,proto3,oneof" json:"kom_time,omitempty"`
	KomEffortId *string              `protobuf:"bytes,4,opt,name=kom_effort_id,json=komEffortId,proto3,oneof" json:"kom_effort_id,omitempty"`
	// The owner-only personal best (used in private-segment views).
	PrTime        *durationpb.Duration `protobuf:"bytes,5,opt,name=pr_time,json=prTime,proto3,oneof" json:"pr_time,omitempty"`
	PrEffortId    *string              `protobuf:"bytes,6,opt,name=pr_effort_id,json=prEffortId,proto3,oneof" json:"pr_effort_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SegmentStats) Reset() {
	*x = SegmentStats{}
	mi := &file_cairn_v1_segment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentStats) ProtoMessage() {}

func (x *SegmentStats) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_v1_segment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentStats.ProtoReflect.Descriptor instead.
func (*SegmentStats) Descriptor() ([]byte, []int) {
	return file_cairn_v1_segment_proto_rawDescGZIP(), []int{1}
}

func (x *SegmentStats) GetEffortCount() int32 {
	if x != nil {
		return x.EffortCount
	}
	return 0
}

func (x *SegmentStats) GetAthleteCount() int32 {
	if x != nil {
		return x.AthleteCount
	}
	return 0
}

func (x *SegmentStats) GetKomTime() *durationpb.Duration {
	if x != nil {
		return x.KomTime
	}
	return nil
}

func (x *SegmentStats) GetKomEffortId() string {
	if x != nil && x.KomEffortId != nil {
		return *x.KomEffortId
	}
	return ""
}

func (x *SegmentStats) GetPrTime() *durationpb.Duration {
	if x != nil {
		return x.PrTime
	}
	return nil
}

func (x *SegmentStats) GetPrEffortId() string {
	if x != nil && x.PrEffortId != nil {
		return *x.PrEffortId
	}
	return ""
}

type SegmentEffort struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SegmentId  string                 `protobuf:"bytes,2,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	ActivityId string                 `protobuf:"bytes,3,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	// Which activity-source stream was matched — for cross-source dedup
	// and stream-toggle UX.
	ActivitySourceId string `protobuf:"bytes,4,opt,name=activity_source_id,json=activitySourceId,proto3" json:"activity_source_id,omitempty"`
	UserId           string `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// When the effort happened (start of the segment on the activity's clock).
	StartTime *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Elapsed   *durationpb.Duration   `protobuf:"bytes,7,opt,name=elapsed,proto3" json:"elapsed,omitempty"`
	Moving    *durationpb.Duration   `protobuf:"bytes,8,opt,name=moving,proto3" json:"moving,omitempty"`
	// Stream offsets within the source's stream.
	StartOffset int32 `protobuf:"varint,9,opt,name=start_offset,json=startOffset,proto3" json:"start_offset,omitempty"`
	EndOffset   int32 `protobuf:"varint,10,opt,name=end_offset,json=endOffset,proto3" json:"end_offset,omitempty"`
	// Summary metrics over the segment.
	AvgHeartRateBpm *int32   `protobuf:"varint,11,opt,name=avg_heart_rate_bpm,json=avgHeartRateBpm,proto3,oneof" json:"avg_heart_rate_bpm,omitempty"`
	MaxHeartRateBpm *int32   `protobuf:"varint,12,opt,name=max_heart_rate_bpm,json=maxHeartRateBpm,proto3,oneof" json:"max_heart_rate_bpm,omitempty"`
	AvgPowerW       *int32   `protobuf:"varint,13,opt,name=avg_power_w,json=avgPowerW,proto3,oneof" json:"avg_power_w,omitempty"`
	AvgCadence      *int32   `protobuf:"varint,14,opt,name=avg_cadence,json=avgCadence,proto3,oneof" json:"avg_cadence,omitempty"`
	AvgSpeedMps     *float64 `protobuf:"fixed64,15,opt,name=avg_speed_mps,json=avgSpeedMps,proto3,oneof" json:"avg_speed_mps,omitempty"`
	// Where this effort ranks for this user (1 = current PR; 0 = unranked).
	PersonalRank int32 `protobuf:"varint,16,opt,name=personal_rank,json=personalRank,proto3" json:"personal_rank,omitempty"`
	// Where this effort ranks instance-wide (only for SCOPE_INSTANCE segments).
	InstanceRank int32 `protobuf:"varint,17,opt,name=instance_rank,json=instanceRank,proto3" json:"instance_rank,omitempty"`
	// True if this effort newly set the user's PR. Used to suppress
	// duplicate PR notifications when reimporting.
	IsPersonalRecord bool `protobuf:"varint,18,opt,name=is_personal_record,json=isPersonalRecord,proto3" json:"is_personal_record,omitempty"`
	// True if this effort newly set the instance KOM.
	IsInstanceRecord bool `protobuf:"varint,19,opt,name=is_instance_record,json=isInstanceRecord,proto3" json:"is_instance_record,omitempty"`
	// Strava reports provider-known efforts on its activity payloads
	// (ProviderSegmentEffort). For source="strava" Cairn segments, Cairn
	// computes the effort independently; if Strava also reported one, the
	// provider's id is stored here for reconciliation/audit.
	ProviderEffortExternalId *string                `protobuf:"bytes,20,opt,name=provider_effort_external_id,json=providerEffortExternalId,proto3,oneof" json:"provider_effort_external_id,omitempty"`
	CreatedAt                *timestamppb.Timestamp `protobuf:"bytes,21,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *SegmentEffort) Reset() {
	*x = SegmentEffort{}
	mi := &file_cairn_v1_segment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentEffort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentEffort) ProtoMessage() {}

func (x *SegmentEffort) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_v1_segment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentEffort.ProtoReflect.Descriptor instead.
func (*SegmentEffort) Descriptor() ([]byte, []int) {
	return file_cairn_v1_segment_proto_rawDescGZIP(), []int{2}
}

func (x *SegmentEffort) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SegmentEffort) GetSegmentId() string {
	if x != nil {
		return x.SegmentId
	}
	return ""
}

func (x *SegmentEffort) GetActivityId() string {
	if x != nil {
		return x.ActivityId
	}
	return ""
}

func (x *SegmentEffort) GetActivitySourceId() string {
	if x != nil {
		return x.ActivitySourceId
	}
	return ""
}

func (x *SegmentEffort) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SegmentEffort) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *SegmentEffort) GetElapsed() *durationpb.Duration {
	if x != nil {
		return x.Elapsed
	}
	return nil
}

func (x *SegmentEffort) GetMoving() *durationpb.Duration {
	if x != nil {
		return x.Moving
	}
	return nil
}

func (x *SegmentEffort) GetStartOffset() int32 {
	if x != nil {
		return x.StartOffset
	}
	return 0
}

func (x *SegmentEffort) GetEndOffset() int32 {
	if x != nil {
		return x.EndOffset
	}
	return 0
}

func (x *SegmentEffort) GetAvgHeartRateBpm() int32 {
	if x != nil && x.AvgHeartRateBpm != nil {
		return *x.AvgHeartRateBpm
	}
	return 0
}

func (x *SegmentEffort) GetMaxHeartRateBpm() int32 {
	if x != nil && x.MaxHeartRateBpm != nil {
		return *x.MaxHeartRateBpm
	}
	return 0
}

func (x *SegmentEffort) GetAvgPowerW() int32 {
	if x != nil && x.AvgPowerW != nil {
		return *x.AvgPowerW
	}
	return 0
}

func (x *SegmentEffort) GetAvgCadence() int32 {
	if x != nil && x.AvgCadence != nil {
		return *x.AvgCadence
	}
	return 0
}

func (x *SegmentEffort) GetAvgSpeedMps() float64 {
	if x != nil && x.AvgSpeedMps != nil {
		return *x.AvgSpeedMps
	}
	return 0
}

func (x *SegmentEffort) GetPersonalRank() int32 {
	if x != nil {
		return x.PersonalRank
	}
	return 0
}

func (x *SegmentEffort) GetInstanceRank() int32 {
	if x != nil {
		return x.InstanceRank
	}
	return 0
}

func (x *SegmentEffort) GetIsPersonalRecord() bool {
	if x != nil {
		return x.IsPersonalRecord
	}
	return false
}

func (x *SegmentEffort) GetIsInstanceRecord() bool {
	if x != nil {
		return x.IsInstanceRecord
	}
	return false
}

func (x *SegmentEffort) GetProviderEffortExternalId() string {
	if x != nil && x.ProviderEffortExternalId != nil {
		return *x.ProviderEffortExternalId
	}
	return ""
}

func (x *SegmentEffort) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListSegmentsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter by source ("strava", "cairn"), empty = all.
	Sources []string `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
	// Filter by visibility.
	Scopes []SegmentScope `protobuf:"varint,2,rep,packed,name=scopes,proto3,enum=cairn.v1.SegmentScope" json:"scopes,omitempty"`
	// Activity type filter (RIDE etc.).
	ActivityTypes []ActivityType `protobuf:"varint,3,rep,packed,name=activity_types,json=activityTypes,proto3,enum=cairn.v1.ActivityType" json:"activity_types,omitempty"`
	// Only segments the caller has at least one effort on.
	OnlyWithEfforts bool `protobuf:"varint,4,opt,name=only_with_efforts,json=onlyWithEfforts,proto3" json:"only_with_efforts,omitempty"`
	// Only starred segments (Strava only).
	OnlyStarred bool `protobuf:"varint,5,opt,name=only_starred,json=onlyStarred,proto3" json:"only_starred,omitempty"`
	// Text search on name + description.
	Query         string       `protobuf:"bytes,6,opt,name=query,proto3" json:"query,omitempty"`
	Sort          SegmentSort  `protobuf:"varint,7,opt,name=sort,proto3,enum=cairn.v1.SegmentSort" json:"sort,omitempty"`
	Page          *PageRequest `protobuf:"bytes,8,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSegmentsRequest) Reset() {
	*x = ListSegmentsRequest{}
	mi := &file_cairn_v1_segment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSegmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSegmentsRequest) ProtoMessage() {}

func (x *ListSegmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_v1_segment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSegmentsRequest.ProtoReflect.Descriptor instead.
func (*ListSegmentsRequest) Descriptor() ([]byte, []int) {
	return file_cairn_v1_segment_proto_rawDescGZIP(), []int{3}
}

func (x *ListSegmentsRequest) GetSources() []string {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *ListSegmentsRequest) GetScopes() []SegmentScope {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *ListSegmentsRequest) GetActivityTypes() []ActivityType {
	if x != nil {
		return x.ActivityTypes
	}
	return nil
}

func (x *ListSegmentsRequest) GetOnlyWithEfforts() bool {
	if x != nil {
		return x.OnlyWithEfforts
	}
	return false
}

func (x *ListSegmentsRequest) GetOnlyStarred() bool {
	if x != nil {
		return x.OnlyStarred
	}
	return false
}

func (x *ListSegmentsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ListSegmentsRequest) GetSort() SegmentSort {
	if x != nil {
		return x.Sort
	}
	return SegmentSort_SEGMENT_SORT_UNSPECIFIED
}

func (x *ListSegmentsRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListSegmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Segments      []*Segment             `protobuf:"bytes,1,rep,name=segments,proto3" json:"segments,omitempty"`
	Page          *PageResponse          `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSegmentsResponse) Reset() {
	*x = ListSegmentsResponse{}
	mi := &file_cairn_v1_segment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSegmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSegmentsResponse) ProtoMessage() {}

func (x *ListSegmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_v1_segment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSegmentsResponse.ProtoReflect.Descriptor instead.
func (*ListSegmentsResponse) Descriptor() ([]byte, []int) {
	return file_cairn_v1_segment_proto_rawDescGZIP(), []int{4}
}

func (x *ListSegmentsResponse) GetSegments() []*Segment {
	if x != nil {
		return x.Segments
	}
	return nil
}

func (x *ListSegmentsResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type GetSegmentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// If true, include effort previews (top N) in the response.
	IncludeTopEfforts bool `protobuf:"varint,2,opt,name=include_top_efforts,json=includeTopEfforts,proto3" json:"include_top_efforts,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetSegmentRequest) Reset() {
	*x = GetSegmentRequest{}
	mi := &file_cairn_v1_segment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSegmentRequest) ProtoMessage() {}

func (x *GetSegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_v1_segment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSegmentRequest.ProtoReflect.Descriptor instead.
func (*GetSegmentRequest) Descriptor() ([]byte, []int) {
	return file_cairn_v1_segment_proto_rawDescGZIP(), []int{5}
}

func (x *GetSegmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetSegmentRequest) GetIncludeTopEfforts() bool {
	if x != nil {
		return x.IncludeTopEfforts
	}
	return false
}

type GetSegmentResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Segment *Segment               `protobuf:"bytes,1,opt,name=segment,proto3" json:"segment,omitempty"`
	// Populated only when include_top_efforts is true.
	TopEfforts    []*SegmentEffort `protobuf:"bytes,2,rep,name=top_efforts,json=topEfforts,proto3" json:"top_efforts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSegmentResponse) Reset() {
	*x = GetSegmentResponse{}
	mi := &file_cairn_v1_segment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSegmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSegmentResponse) ProtoMessage() {}

func (x *GetSegmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_v1_segment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSegmentResponse.ProtoReflect.Descriptor instead.
func (*GetSegmentResponse) Descriptor() ([]byte, []int) {
	return file_cairn_v1_segment_proto_rawDescGZIP(), []int{6}
}

func (x *GetSegmentResponse) GetSegment() *Segment {
	if x != nil {
		return x.Segment
	}
	return nil
}

func (x *GetSegmentResponse) GetTopEfforts() []*SegmentEffort {
	if x != nil {
		return x.TopEfforts
	}
	return nil
}

type CreateSegmentRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Name         string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description  string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ActivityType ActivityType           `protobuf:"varint,3,opt,name=activity_type,json=activityType,proto3,enum=cairn.v1.ActivityType" json:"activity_type,omitempty"`
	Polyline     *EncodedPolyline       `protobuf:"bytes,4,opt,name=polyline,proto3" json:"polyline,omitempty"`
	Scope        SegmentScope           `protobuf:"varint,5,opt,name=scope,proto3,enum=cairn.v1.SegmentScope" json:"scope,omitempty"`
	// Optional tuning of matching tolerances.
	MatchCorridorM       *float64 `protobuf:"fixed64,6,opt,name=match_corridor_m,json=matchCorridorM,proto3,oneof" json:"match_corridor_m,omitempty"`
	MatchStartToleranceM *float64 `protobuf:"fixed64,7,opt,name=match_start_tolerance_m,json=matchStartToleranceM,proto3,oneof" json:"match_start_tolerance_m,omitempty"`
	MatchEndToleranceM   *float64 `protobuf:"fixed64,8,opt,name=match_end_tolerance_m,json=matchEndToleranceM,proto3,oneof" json:"match_end_tolerance_m,omitempty"`
	Bidirectional        bool     `protobuf:"varint,9,opt,name=bidirectional,proto3" json:"bidirectional,omitempty"`
	// If true, queues a RematchSegment job after creation to backfill
	// historical efforts. Default true.
	BackfillEfforts bool `protobuf:"varint,10,opt,name=backfill_efforts,json=backfillEfforts,proto3" json:"backfill_efforts,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateSegmentRequest) Reset() {
	*x = CreateSegmentRequest{}
	mi := &file_cairn_v1_segment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSegmentRequest) ProtoMessage() {}

func (x *CreateSegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_v1_segment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSegmentRequest.ProtoReflect.Descriptor instead.
func (*CreateSegmentRequest) Descriptor() ([]byte, []int) {
	return file_cairn_v1_segment_proto_rawDescGZIP(), []int{7}
}

func (x *CreateSegmentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSegmentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateSegmentRequest) GetActivityType() ActivityType {
	if x != nil {
		return x.ActivityType
	}
	return ActivityType_ACTIVITY_TYPE_UNSPECIFIED
}

func (x *CreateSegmentRequest) GetPolyline() *EncodedPolyline {
	if x != nil {
		return x.Polyline
	}
	return nil
}

func (x *CreateSegmentRequest) GetScope() SegmentScope {
	if x != nil {
		return x.Scope
	}
	return SegmentScope_SEGMENT_SCOPE_UNSPECIFIED
}

func (x *CreateSegmentRequest) GetMatchCorridorM() float64 {
	if x != nil && x.MatchCorridorM != nil {
		return *x.MatchCorridorM
	}
	return 0
}

func (x *CreateSegmentRequest) GetMatchStartToleranceM() float64 {
	if x != nil && x.MatchStartToleranceM != nil {
		return *x.MatchStartToleranceM
	}
	return 0
}

func (x *CreateSegmentRequest) GetMatchEndToleranceM() float64 {
	if x != nil && x.MatchEndToleranceM != nil {
		return *x.MatchEndToleranceM
	}
	return 0
}

func (x *CreateSegmentRequest) GetBidirectional() bool {
	if x != nil {
		return x.Bidirectional
	}
	return false
}

func (x *CreateSegmentRequest) GetBackfillEfforts() bool {
	if x != nil {
		return x.BackfillEfforts
	}
	return false
}

type CreateSegmentResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Segment *Segment               `protobuf:"bytes,1,opt,name=segment,proto3" json:"segment,omitempty"`
	// The backfill job, if backfill_efforts was true.
	BackfillJobId *string `protobuf:"bytes,2,opt,name=backfill_job_id,json=backfillJobId,proto3,oneof" json:"backfill_job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSegmentResponse) Reset() {
	*x = CreateSegmentResponse{}
	mi := &file_cairn_v1_segment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSegmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSegmentResponse) ProtoMessage() {}

func (x *CreateSegmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_v1_segment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSegmentResponse.ProtoReflect.Descriptor instead.
func (*CreateSegmentResponse) Descriptor() ([]byte, []int) {
	return file_cairn_v1_segment_proto_rawDescGZIP(), []int{8}
}

func (x *CreateSegmentResponse) GetSegment() *Segment {
	if x != nil {
		return x.Segment
	}
	return nil
}

func (x *CreateSegmentResponse) GetBackfillJobId() string {
	if x != nil && x.BackfillJobId != nil {
		return *x.BackfillJobId
	}
	return ""
}

type UpdateSegmentRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FieldMask            []string               `protobuf:"bytes,2,rep,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	Name                 *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description          *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Scope                *SegmentScope          `protobuf:"varint,5,opt,name=scope,proto3,enum=cairn.v1.SegmentScope,oneof" json:"scope,omitempty"`
	MatchCorridorM       *float64               `protobuf:"fixed64,6,opt,name=match_corridor_m,json=matchCorridorM,proto3,oneof" json:"match_corridor_m,omitempty"`
	MatchStartToleranceM *float64               `protobuf:"fixed64,7,opt,name=match_start_tolerance_m,json=matchStartToleranceM,proto3,oneof" json:"match_start_tolerance_m,omitempty"`
	MatchEndToleranceM   *float64               `protobuf:"fixed64,8,opt,name=match_end_tolerance_m,json=matchEndToleranceM,proto3,oneof" json:"match_end_tolerance_m,omitempty"`
	Bidirectional        *bool                  `protobuf:"varint,9,opt,name=bidirectional,proto3,oneof" json:"bidirectional,omitempty"`
	Starred              *bool                  `protobuf:"varint,10,opt,name=starred,proto3,oneof" json:"starred,omitempty"` // Strava: pushes to provider
	// Polyline edits are not allowed on segments with existing efforts;
	// create a new segment instead. The Core rejects polyline changes when
	// SegmentStats.effort_count > 0.
	Polyline      *EncodedPolyline `protobuf:"bytes,11,opt,name=polyline,proto3,oneof" json:"polyline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSegmentRequest) Reset() {
	*x = UpdateSegmentRequest{}
	mi := &file_cairn_v1_segment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSegmentRequest) ProtoMessage() {}

func (x *UpdateSegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_v1_segment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSegmentRequest.ProtoReflect.Descriptor instead.
func (*UpdateSegmentRequest) Descriptor() ([]byte, []int) {
	return file_cairn_v1_segment_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateSegmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSegmentRequest) GetFieldMask() []string {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

func (x *UpdateSegmentRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateSegmentRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateSegmentRequest) GetScope() SegmentScope {
	if x != nil && x.Scope != nil {
		return *x.Scope
	}
	return SegmentScope_SEGMENT_SCOPE_UNSPECIFIED
}

func (x *UpdateSegmentRequest) GetMatchCorridorM() float64 {
	if x != nil && x.MatchCorridorM != nil {
		return *x.MatchCorridorM
	}
	return 0
}

func (x *UpdateSegmentRequest) GetMatchStartToleranceM() float64 {
	if x != nil && x.MatchStartToleranceM != nil {
		return *x.MatchStartToleranceM
	}
	return 0
}

func (x *UpdateSegmentRequest) GetMatchEndToleranceM() float64 {
	if x != nil && x.MatchEndToleranceM != nil {
		return *x.MatchEndToleranceM
	}
	return 0
}

func (x *UpdateSegmentRequest) GetBidirectional() bool {
	if x != nil && x.Bidirectional != nil {
		return *x.Bidirectional
	}
	return false
}

func (x *UpdateSegmentRequest) GetStarred() bool {
	if x != nil && x.Starred != nil {
		return *x.Starred
	}
	return false
}

func (x *UpdateSegmentRequest) GetPolyline() *EncodedPolyline {
	if x != nil {
		return x.Polyline
	}
	return nil
}

type UpdateSegmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Segment       *Segment               `protobuf:"bytes,1,opt,name=segment,proto3" json:"segment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSegmentResponse) Reset() {
	*x = UpdateSegmentResponse{}
	mi := &file_cairn_v1_segment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSegmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSegmentResponse) ProtoMessage() {}

func (x *UpdateSegmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_v1_segment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSegmentResponse.ProtoReflect.Descriptor instead.
func (*UpdateSegmentResponse) Descriptor() ([]byte, []int) {
	return file_cairn_v1_segment_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateSegmentResponse) GetSegment() *Segment {
	if x != nil {
		return x.Segment
	}
	return nil
}

type DeleteSegmentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// True keeps recorded SegmentEffort rows (preserves PR history at the
	// cost of dangling references). False cascade-deletes efforts.
	KeepEfforts   bool `protobuf:"varint,2,opt,name=keep_efforts,json=keepEfforts,proto3" json:"keep_efforts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSegmentRequest) Reset() {
	*x = DeleteSegmentRequest{}
	mi := &file_cairn_v1_segment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSegmentRequest) ProtoMessage() {}

func (x *DeleteSegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_v1_segment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSegmentRequest.ProtoReflect.Descriptor instead.
func (*DeleteSegmentRequest) Descriptor() ([]byte, []int) {
	return file_cairn_v1_segment_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteSegmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteSegmentRequest) GetKeepEfforts() bool {
	if x != nil {
		return x.KeepEfforts
	}
	return false
}

type DeleteSegmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSegmentResponse) Reset() {
	*x = DeleteSegmentResponse{}
	mi := &file_cairn_v1_segment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSegmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSegmentResponse) ProtoMessage() {}

func (x *DeleteSegmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_v1_segment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSegmentResponse.ProtoReflect.Descriptor instead.
func (*DeleteSegmentResponse) Descriptor() ([]byte, []int) {
	return file_cairn_v1_segment_proto_rawDescGZIP(), []int{12}
}

type SearchSegmentsInBoundingBoxRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Bbox  *BoundingBox           `protobuf:"bytes,1,opt,name=bbox,proto3" json:"bbox,omitempty"`
	// Optional filter by activity type.
	ActivityTypes []ActivityType `protobuf:"varint,2,rep,packed,name=activity_types,json=activityTypes,proto3,enum=cairn.v1.ActivityType" json:"activity_types,omitempty"`
	// Max results (server-capped). Returned in unspecified order; client
	// typically renders all of them as map overlays.
	Limit int32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	// Include instance-scoped segments from other users.
	IncludeInstanceSegments bool `protobuf:"varint,4,opt,name=include_instance_segments,json=includeInstanceSegments,proto3" json:"include_instance_segments,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *SearchSegmentsInBoundingBoxRequest) Reset() {
	*x = SearchSegmentsInBoundingBoxRequest{}
	mi := &file_cairn_v1_segment_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSegmentsInBoundingBoxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSegmentsInBoundingBoxRequest) ProtoMessage() {}

func (x *SearchSegmentsInBoundingBoxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_v1_segment_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSegmentsInBoundingBoxRequest.ProtoReflect.Descriptor instead.
func (*SearchSegmentsInBoundingBoxRequest) Descriptor() ([]byte, []int) {
	return file_cairn_v1_segment_proto_rawDescGZIP(), []int{13}
}

func (x *SearchSegmentsInBoundingBoxRequest) GetBbox() *BoundingBox {
	if x != nil {
		return x.Bbox
	}
	return nil
}

func (x *SearchSegmentsInBoundingBoxRequest) GetActivityTypes() []ActivityType {
	if x != nil {
		return x.ActivityTypes
	}
	return nil
}

func (x *SearchSegmentsInBoundingBoxRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchSegmentsInBoundingBoxRequest) GetIncludeInstanceSegments() bool {
	if x != nil {
		return x.IncludeInstanceSegments
	}
	return false
}

type SearchSegmentsInBoundingBoxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Segments      []*Segment             `protobuf:"bytes,1,rep,name=segments,proto3" json:"segments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSegmentsInBoundingBoxResponse) Reset() {
	*x = SearchSegmentsInBoundingBoxResponse{}
	mi := &file_cairn_v1_segment_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSegmentsInBoundingBoxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSegmentsInBoundingBoxResponse) ProtoMessage() {}

func (x *SearchSegmentsInBoundingBoxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_v1_segment_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSegmentsInBoundingBoxResponse.ProtoReflect.Descriptor instead.
func (*SearchSegmentsInBoundingBoxResponse) Descriptor() ([]byte, []int) {
	return file_cairn_v1_segment_proto_rawDescGZIP(), []int{14}
}

func (x *SearchSegmentsInBoundingBoxResponse) GetSegments() []*Segment {
	if x != nil {
		return x.Segments
	}
	return nil
}

type ListSegmentEffortsRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SegmentId string                 `protobuf:"bytes,1,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	TimeRange *TimeRange             `protobuf:"bytes,2,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	// For SCOPE_INSTANCE: filter to a specific user (empty = all users).
	UserId *string      `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	Page   *PageRequest `protobuf:"bytes,4,opt,name=page,proto3" json:"page,omitempty"`
	// Sort: SEGMENT_EFFORT_SORT_ELAPSED_ASC is the leaderboard sort.
	Sort          SegmentEffortSort `protobuf:"varint,5,opt,name=sort,proto3,enum=cairn.v1.SegmentEffortSort" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSegmentEffortsRequest) Reset() {
	*x = ListSegmentEffortsRequest{}
	mi := &file_cairn_v1_segment_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSegmentEffortsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSegmentEffortsRequest) ProtoMessage() {}

func (x *ListSegmentEffortsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_v1_segment_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSegmentEffortsRequest.ProtoReflect.Descriptor instead.
func (*ListSegmentEffortsRequest) Descriptor() ([]byte, []int) {
	return file_cairn_v1_segment_proto_rawDescGZIP(), []int{15}
}

func (x *ListSegmentEffortsRequest) GetSegmentId() string {
	if x != nil {
		return x.SegmentId
	}
	return ""
}

func (x *ListSegmentEffortsRequest) GetTimeRange() *TimeRange {
	if x != nil {
		return x.TimeRange
	}
	return nil
}

func (x *ListSegmentEffortsRequest) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *ListSegmentEffortsRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListSegmentEffortsRequest) GetSort() SegmentEffortSort {
	if x != nil {
		return x.Sort
	}
	return SegmentEffortSort_SEGMENT_EFFORT_SORT_UNSPECIFIED
}

type ListSegmentEffortsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Efforts       []*SegmentEffort       `protobuf:"bytes,1,rep,name=efforts,proto3" json:"efforts,omitempty"`
	Page          *PageResponse          `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSegmentEffortsResponse) Reset() {
	*x = ListSegmentEffortsResponse{}
	mi := &file_cairn_v1_segment_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSegmentEffortsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSegmentEffortsResponse) ProtoMessage() {}

func (x *ListSegmentEffortsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_v1_segment_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSegmentEffortsResponse.ProtoReflect.Descriptor instead.
func (*ListSegmentEffortsResponse) Descriptor() ([]byte, []int) {
	return file_cairn_v1_segment_proto_rawDescGZIP(), []int{16}
}

func (x *ListSegmentEffortsResponse) GetEfforts() []*SegmentEffort {
	if x != nil {
		return x.Efforts
	}
	return nil
}

func (x *ListSegmentEffortsResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListMySegmentEffortsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SegmentId     string                 `protobuf:"bytes,1,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	TimeRange     *TimeRange             `protobuf:"bytes,2,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	Page          *PageRequest           `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMySegmentEffortsRequest) Reset() {
	*x = ListMySegmentEffortsRequest{}
	mi := &file_cairn_v1_segment_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMySegmentEffortsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMySegmentEffortsRequest) ProtoMessage() {}

func (x *ListMySegmentEffortsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_v1_segment_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMySegmentEffortsRequest.ProtoReflect.Descriptor instead.
func (*ListMySegmentEffortsRequest) Descriptor() ([]byte, []int) {
	return file_cairn_v1_segment_proto_rawDescGZIP(), []int{17}
}

func (x *ListMySegmentEffortsRequest) GetSegmentId() string {
	if x != nil {
		return x.SegmentId
	}
	return ""
}

func (x *ListMySegmentEffortsRequest) GetTimeRange() *TimeRange {
	if x != nil {
		return x.TimeRange
	}
	return nil
}

func (x *ListMySegmentEffortsRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListMySegmentEffortsResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Efforts []*SegmentEffort       `protobuf:"bytes,1,rep,name=efforts,proto3" json:"efforts,omitempty"`
	Page    *PageResponse          `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	// The caller's PR effort on this segment (if any). Convenient to render
	// a banner above the table.
	PersonalRecord *SegmentEffort `protobuf:"bytes,3,opt,name=personal_record,json=personalRecord,proto3,oneof" json:"personal_record,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListMySegmentEffortsResponse) Reset() {
	*x = ListMySegmentEffortsResponse{}
	mi := &file_cairn_v1_segment_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMySegmentEffortsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMySegmentEffortsResponse) ProtoMessage() {}

func (x *ListMySegmentEffortsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_v1_segment_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMySegmentEffortsResponse.ProtoReflect.Descriptor instead.
func (*ListMySegmentEffortsResponse) Descriptor() ([]byte, []int) {
	return file_cairn_v1_segment_proto_rawDescGZIP(), []int{18}
}

func (x *ListMySegmentEffortsResponse) GetEfforts() []*SegmentEffort {
	if x != nil {
		return x.Efforts
	}
	return nil
}

func (x *ListMySegmentEffortsResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListMySegmentEffortsResponse) GetPersonalRecord() *SegmentEffort {
	if x != nil {
		return x.PersonalRecord
	}
	return nil
}

type GetSegmentLeaderboardRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SegmentId string                 `protobuf:"bytes,1,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	// Restrict to a time window — "all-time", "this year", "last 30d", etc.
	// Empty = all-time.
	TimeRange *TimeRange `protobuf:"bytes,2,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	// Optional age/sex filters. Privacy: only applied if user profiles share
	// sex/age, otherwise ignored.
	BiologicalSex *BiologicalSex `protobuf:"varint,3,opt,name=biological_sex,json=biologicalSex,proto3,enum=cairn.v1.BiologicalSex,oneof" json:"biological_sex,omitempty"`
	Page          *PageRequest   `protobuf:"bytes,4,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSegmentLeaderboardRequest) Reset() {
	*x = GetSegmentLeaderboardRequest{}
	mi := &file_cairn_v1_segment_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSegmentLeaderboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSegmentLeaderboardRequest) ProtoMessage() {}

func (x *GetSegmentLeaderboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_v1_segment_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSegmentLeaderboardRequest.ProtoReflect.Descriptor instead.
func (*GetSegmentLeaderboardRequest) Descriptor() ([]byte, []int) {
	return file_cairn_v1_segment_proto_rawDescGZIP(), []int{19}
}

func (x *GetSegmentLeaderboardRequest) GetSegmentId() string {
	if x != nil {
		return x.SegmentId
	}
	return ""
}

func (x *GetSegmentLeaderboardRequest) GetTimeRange() *TimeRange {
	if x != nil {
		return x.TimeRange
	}
	return nil
}

func (x *GetSegmentLeaderboardRequest) GetBiologicalSex() BiologicalSex {
	if x != nil && x.BiologicalSex != nil {
		return *x.BiologicalSex
	}
	return BiologicalSex_BIOLOGICAL_SEX_UNSPECIFIED
}

func (x *GetSegmentLeaderboardRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type LeaderboardEntry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Rank            int32                  `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserDisplayName string                 `protobuf:"bytes,3,opt,name=user_display_name,json=userDisplayName,proto3" json:"user_display_name,omitempty"`
	UserAvatarUrl   *string                `protobuf:"bytes,4,opt,name=user_avatar_url,json=userAvatarUrl,proto3,oneof" json:"user_avatar_url,omitempty"`
	Elapsed         *durationpb.Duration   `protobuf:"bytes,5,opt,name=elapsed,proto3" json:"elapsed,omitempty"`
	StartTime       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EffortId        string                 `protobuf:"bytes,7,opt,name=effort_id,json=effortId,proto3" json:"effort_id,omitempty"`
	ActivityId      string                 `protobuf:"bytes,8,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LeaderboardEntry) Reset() {
	*x = LeaderboardEntry{}
	mi := &file_cairn_v1_segment_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardEntry) ProtoMessage() {}

func (x *LeaderboardEntry) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_v1_segment_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardEntry.ProtoReflect.Descriptor instead.
func (*LeaderboardEntry) Descriptor() ([]byte, []int) {
	return file_cairn_v1_segment_proto_rawDescGZIP(), []int{20}
}

func (x *LeaderboardEntry) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *LeaderboardEntry) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LeaderboardEntry) GetUserDisplayName() string {
	if x != nil {
		return x.UserDisplayName
	}
	return ""
}

func (x *LeaderboardEntry) GetUserAvatarUrl() string {
	if x != nil && x.UserAvatarUrl != nil {
		return *x.UserAvatarUrl
	}
	return ""
}

func (x *LeaderboardEntry) GetElapsed() *durationpb.Duration {
	if x != nil {
		return x.Elapsed
	}
	return nil
}

func (x *LeaderboardEntry) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *LeaderboardEntry) GetEffortId() string {
	if x != nil {
		return x.EffortId
	}
	return ""
}

func (x *LeaderboardEntry) GetActivityId() string {
	if x != nil {
		return x.ActivityId
	}
	return ""
}

type GetSegmentLeaderboardResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Entries []*LeaderboardEntry    `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Page    *PageResponse          `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	// The calling user's rank in this leaderboard, if any.
	MyRank        *int32            `protobuf:"varint,3,opt,name=my_rank,json=myRank,proto3,oneof" json:"my_rank,omitempty"`
	MyEntry       *LeaderboardEntry `protobuf:"bytes,4,opt,name=my_entry,json=myEntry,proto3,oneof" json:"my_entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSegmentLeaderboardResponse) Reset() {
	*x = GetSegmentLeaderboardResponse{}
	mi := &file_cairn_v1_segment_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSegmentLeaderboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSegmentLeaderboardResponse) ProtoMessage() {}

func (x *GetSegmentLeaderboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_v1_segment_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSegmentLeaderboardResponse.ProtoReflect.Descriptor instead.
func (*GetSegmentLeaderboardResponse) Descriptor() ([]byte, []int) {
	return file_cairn_v1_segment_proto_rawDescGZIP(), []int{21}
}

func (x *GetSegmentLeaderboardResponse) GetEntries() []*LeaderboardEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *GetSegmentLeaderboardResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *GetSegmentLeaderboardResponse) GetMyRank() int32 {
	if x != nil && x.MyRank != nil {
		return *x.MyRank
	}
	return 0
}

func (x *GetSegmentLeaderboardResponse) GetMyEntry() *LeaderboardEntry {
	if x != nil {
		return x.MyEntry
	}
	return nil
}

type RematchActivityRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ActivityId string                 `protobuf:"bytes,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	// If non-empty, match only against these segments; otherwise all eligible.
	SegmentIds    []string `protobuf:"bytes,2,rep,name=segment_ids,json=segmentIds,proto3" json:"segment_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RematchActivityRequest) Reset() {
	*x = RematchActivityRequest{}
	mi := &file_cairn_v1_segment_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RematchActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RematchActivityRequest) ProtoMessage() {}

func (x *RematchActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_v1_segment_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RematchActivityRequest.ProtoReflect.Descriptor instead.
func (*RematchActivityRequest) Descriptor() ([]byte, []int) {
	return file_cairn_v1_segment_proto_rawDescGZIP(), []int{22}
}

func (x *RematchActivityRequest) GetActivityId() string {
	if x != nil {
		return x.ActivityId
	}
	return ""
}

func (x *RematchActivityRequest) GetSegmentIds() []string {
	if x != nil {
		return x.SegmentIds
	}
	return nil
}

type RematchActivityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RematchActivityResponse) Reset() {
	*x = RematchActivityResponse{}
	mi := &file_cairn_v1_segment_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RematchActivityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RematchActivityResponse) ProtoMessage() {}

func (x *RematchActivityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_v1_segment_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RematchActivityResponse.ProtoReflect.Descriptor instead.
func (*RematchActivityResponse) Descriptor() ([]byte, []int) {
	return file_cairn_v1_segment_proto_rawDescGZIP(), []int{23}
}

func (x *RematchActivityResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type RematchSegmentRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SegmentId string                 `protobuf:"bytes,1,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	// Match only against the caller's activities within this time range.
	TimeRange     *TimeRange `protobuf:"bytes,2,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RematchSegmentRequest) Reset() {
	*x = RematchSegmentRequest{}
	mi := &file_cairn_v1_segment_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RematchSegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RematchSegmentRequest) ProtoMessage() {}

func (x *RematchSegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_v1_segment_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RematchSegmentRequest.ProtoReflect.Descriptor instead.
func (*RematchSegmentRequest) Descriptor() ([]byte, []int) {
	return file_cairn_v1_segment_proto_rawDescGZIP(), []int{24}
}

func (x *RematchSegmentRequest) GetSegmentId() string {
	if x != nil {
		return x.SegmentId
	}
	return ""
}

func (x *RematchSegmentRequest) GetTimeRange() *TimeRange {
	if x != nil {
		return x.TimeRange
	}
	return nil
}

type RematchSegmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RematchSegmentResponse) Reset() {
	*x = RematchSegmentResponse{}
	mi := &file_cairn_v1_segment_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RematchSegmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RematchSegmentResponse) ProtoMessage() {}

func (x *RematchSegmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_v1_segment_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RematchSegmentResponse.ProtoReflect.Descriptor instead.
func (*RematchSegmentResponse) Descriptor() ([]byte, []int) {
	return file_cairn_v1_segment_proto_rawDescGZIP(), []int{25}
}

func (x *RematchSegmentResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

var File_cairn_v1_segment_proto protoreflect.FileDescriptor

const file_cairn_v1_segment_proto_rawDesc = "" +
	"\n" +
	"\x16cairn/v1/segment.proto\x12\bcairn.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17cairn/v1/activity.proto\x1a\x15cairn/v1/common.proto\x1a\x16cairn/v1/metrics.proto\"\xb4\v\n" +
	"\aSegment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12$\n" +
	"\vexternal_id\x18\x03 \x01(\tH\x00R\n" +
	"externalId\x88\x01\x01\x123\n" +
	"\x13external_account_id\x18\x04 \x01(\tH\x01R\x11externalAccountId\x88\x01\x01\x12'\n" +
	"\rowner_user_id\x18\x05 \x01(\tH\x02R\vownerUserId\x88\x01\x01\x12,\n" +
	"\x05scope\x18\x06 \x01(\x0e2\x16.cairn.v1.SegmentScopeR\x05scope\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12;\n" +
	"\ractivity_type\x18\t \x01(\x0e2\x16.cairn.v1.ActivityTypeR\factivityType\x125\n" +
	"\bpolyline\x18\n" +
	" \x01(\v2\x19.cairn.v1.EncodedPolylineR\bpolyline\x128\n" +
	"\fbounding_box\x18\v \x01(\v2\x15.cairn.v1.BoundingBoxR\vboundingBox\x12\x1d\n" +
	"\n" +
	"distance_m\x18\f \x01(\x01R\tdistanceM\x12-\n" +
	"\x10elevation_gain_m\x18\r \x01(\x01H\x03R\x0eelevationGainM\x88\x01\x01\x12-\n" +
	"\x10elevation_loss_m\x18\x0e \x01(\x01H\x04R\x0eelevationLossM\x88\x01\x01\x12+\n" +
	"\x0fmin_elevation_m\x18\x0f \x01(\x01H\x05R\rminElevationM\x88\x01\x01\x12+\n" +
	"\x0fmax_elevation_m\x18\x10 \x01(\x01H\x06R\rmaxElevationM\x88\x01\x01\x12 \n" +
	"\tavg_grade\x18\x11 \x01(\x01H\aR\bavgGrade\x88\x01\x01\x12 \n" +
	"\tmax_grade\x18\x12 \x01(\x01H\bR\bmaxGrade\x88\x01\x01\x12C\n" +
	"\x0eclimb_category\x18\x13 \x01(\x0e2\x17.cairn.v1.ClimbCategoryH\tR\rclimbCategory\x88\x01\x01\x12-\n" +
	"\x10match_corridor_m\x18\x14 \x01(\x01H\n" +
	"R\x0ematchCorridorM\x88\x01\x01\x12:\n" +
	"\x17match_start_tolerance_m\x18\x15 \x01(\x01H\vR\x14matchStartToleranceM\x88\x01\x01\x126\n" +
	"\x15match_end_tolerance_m\x18\x16 \x01(\x01H\fR\x12matchEndToleranceM\x88\x01\x01\x12$\n" +
	"\rbidirectional\x18\x17 \x01(\bR\rbidirectional\x12\x18\n" +
	"\astarred\x18\x18 \x01(\bR\astarred\x12,\n" +
	"\x05stats\x18\x19 \x01(\v2\x16.cairn.v1.SegmentStatsR\x05stats\x129\n" +
	"\n" +
	"created_at\x18\x1a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x1b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x0e\n" +
	"\f_external_idB\x16\n" +
	"\x14_external_account_idB\x10\n" +
	"\x0e_owner_user_idB\x13\n" +
	"\x11_elevation_gain_mB\x13\n" +
	"\x11_elevation_loss_mB\x12\n" +
	"\x10_min_elevation_mB\x12\n" +
	"\x10_max_elevation_mB\f\n" +
	"\n" +
	"_avg_gradeB\f\n" +
	"\n" +
	"_max_gradeB\x11\n" +
	"\x0f_climb_categoryB\x13\n" +
	"\x11_match_corridor_mB\x1a\n" +
	"\x18_match_start_tolerance_mB\x18\n" +
	"\x16_match_end_tolerance_m\"\xd6\x02\n" +
	"\fSegmentStats\x12!\n" +
	"\feffort_count\x18\x01 \x01(\x05R\veffortCount\x12#\n" +
	"\rathlete_count\x18\x02 \x01(\x05R\fathleteCount\x129\n" +
	"\bkom_time\x18\x03 \x01(\v2\x19.google.protobuf.DurationH\x00R\akomTime\x88\x01\x01\x12'\n" +
	"\rkom_effort_id\x18\x04 \x01(\tH\x01R\vkomEffortId\x88\x01\x01\x127\n" +
	"\apr_time\x18\x05 \x01(\v2\x19.google.protobuf.DurationH\x02R\x06prTime\x88\x01\x01\x12%\n" +
	"\fpr_effort_id\x18\x06 \x01(\tH\x03R\n" +
	"prEffortId\x88\x01\x01B\v\n" +
	"\t_kom_timeB\x10\n" +
	"\x0e_kom_effort_idB\n" +
	"\n" +
	"\b_pr_timeB\x0f\n" +
	"\r_pr_effort_id\"\x88\b\n" +
	"\rSegmentEffort\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"segment_id\x18\x02 \x01(\tR\tsegmentId\x12\x1f\n" +
	"\vactivity_id\x18\x03 \x01(\tR\n" +
	"activityId\x12,\n" +
	"\x12activity_source_id\x18\x04 \x01(\tR\x10activitySourceId\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userId\x129\n" +
	"\n" +
	"start_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x123\n" +
	"\aelapsed\x18\a \x01(\v2\x19.google.protobuf.DurationR\aelapsed\x121\n" +
	"\x06moving\x18\b \x01(\v2\x19.google.protobuf.DurationR\x06moving\x12!\n" +
	"\fstart_offset\x18\t \x01(\x05R\vstartOffset\x12\x1d\n" +
	"\n" +
	"end_offset\x18\n" +
	" \x01(\x05R\tendOffset\x120\n" +
	"\x12avg_heart_rate_bpm\x18\v \x01(\x05H\x00R\x0favgHeartRateBpm\x88\x01\x01\x120\n" +
	"\x12max_heart_rate_bpm\x18\f \x01(\x05H\x01R\x0fmaxHeartRateBpm\x88\x01\x01\x12#\n" +
	"\vavg_power_w\x18\r \x01(\x05H\x02R\tavgPowerW\x88\x01\x01\x12$\n" +
	"\vavg_cadence\x18\x0e \x01(\x05H\x03R\n" +
	"avgCadence\x88\x01\x01\x12'\n" +
	"\ravg_speed_mps\x18\x0f \x01(\x01H\x04R\vavgSpeedMps\x88\x01\x01\x12#\n" +
	"\rpersonal_rank\x18\x10 \x01(\x05R\fpersonalRank\x12#\n" +
	"\rinstance_rank\x18\x11 \x01(\x05R\finstanceRank\x12,\n" +
	"\x12is_personal_record\x18\x12 \x01(\bR\x10isPersonalRecord\x12,\n" +
	"\x12is_instance_record\x18\x13 \x01(\bR\x10isInstanceRecord\x12B\n" +
	"\x1bprovider_effort_external_id\x18\x14 \x01(\tH\x05R\x18providerEffortExternalId\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\x15 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\x15\n" +
	"\x13_avg_heart_rate_bpmB\x15\n" +
	"\x13_max_heart_rate_bpmB\x0e\n" +
	"\f_avg_power_wB\x0e\n" +
	"\f_avg_cadenceB\x10\n" +
	"\x0e_avg_speed_mpsB\x1e\n" +
	"\x1c_provider_effort_external_id\"\xd9\x02\n" +
	"\x13ListSegmentsRequest\x12\x18\n" +
	"\asources\x18\x01 \x03(\tR\asources\x12.\n" +
	"\x06scopes\x18\x02 \x03(\x0e2\x16.cairn.v1.SegmentScopeR\x06scopes\x12=\n" +
	"\x0eactivity_types\x18\x03 \x03(\x0e2\x16.cairn.v1.ActivityTypeR\ractivityTypes\x12*\n" +
	"\x11only_with_efforts\x18\x04 \x01(\bR\x0fonlyWithEfforts\x12!\n" +
	"\fonly_starred\x18\x05 \x01(\bR\vonlyStarred\x12\x14\n" +
	"\x05query\x18\x06 \x01(\tR\x05query\x12)\n" +
	"\x04sort\x18\a \x01(\x0e2\x15.cairn.v1.SegmentSortR\x04sort\x12)\n" +
	"\x04page\x18\b \x01(\v2\x15.cairn.v1.PageRequestR\x04page\"q\n" +
	"\x14ListSegmentsResponse\x12-\n" +
	"\bsegments\x18\x01 \x03(\v2\x11.cairn.v1.SegmentR\bsegments\x12*\n" +
	"\x04page\x18\x02 \x01(\v2\x16.cairn.v1.PageResponseR\x04page\"S\n" +
	"\x11GetSegmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\x13include_top_efforts\x18\x02 \x01(\bR\x11includeTopEfforts\"{\n" +
	"\x12GetSegmentResponse\x12+\n" +
	"\asegment\x18\x01 \x01(\v2\x11.cairn.v1.SegmentR\asegment\x128\n" +
	"\vtop_efforts\x18\x02 \x03(\v2\x17.cairn.v1.SegmentEffortR\n" +
	"topEfforts\"\xad\x04\n" +
	"\x14CreateSegmentRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12;\n" +
	"\ractivity_type\x18\x03 \x01(\x0e2\x16.cairn.v1.ActivityTypeR\factivityType\x125\n" +
	"\bpolyline\x18\x04 \x01(\v2\x19.cairn.v1.EncodedPolylineR\bpolyline\x12,\n" +
	"\x05scope\x18\x05 \x01(\x0e2\x16.cairn.v1.SegmentScopeR\x05scope\x12-\n" +
	"\x10match_corridor_m\x18\x06 \x01(\x01H\x00R\x0ematchCorridorM\x88\x01\x01\x12:\n" +
	"\x17match_start_tolerance_m\x18\a \x01(\x01H\x01R\x14matchStartToleranceM\x88\x01\x01\x126\n" +
	"\x15match_end_tolerance_m\x18\b \x01(\x01H\x02R\x12matchEndToleranceM\x88\x01\x01\x12$\n" +
	"\rbidirectional\x18\t \x01(\bR\rbidirectional\x12)\n" +
	"\x10backfill_efforts\x18\n" +
	" \x01(\bR\x0fbackfillEffortsB\x13\n" +
	"\x11_match_corridor_mB\x1a\n" +
	"\x18_match_start_tolerance_mB\x18\n" +
	"\x16_match_end_tolerance_m\"\x85\x01\n" +
	"\x15CreateSegmentResponse\x12+\n" +
	"\asegment\x18\x01 \x01(\v2\x11.cairn.v1.SegmentR\asegment\x12+\n" +
	"\x0fbackfill_job_id\x18\x02 \x01(\tH\x00R\rbackfillJobId\x88\x01\x01B\x12\n" +
	"\x10_backfill_job_id\"\xfa\x04\n" +
	"\x14UpdateSegmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"field_mask\x18\x02 \x03(\tR\tfieldMask\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x01R\vdescription\x88\x01\x01\x121\n" +
	"\x05scope\x18\x05 \x01(\x0e2\x16.cairn.v1.SegmentScopeH\x02R\x05scope\x88\x01\x01\x12-\n" +
	"\x10match_corridor_m\x18\x06 \x01(\x01H\x03R\x0ematchCorridorM\x88\x01\x01\x12:\n" +
	"\x17match_start_tolerance_m\x18\a \x01(\x01H\x04R\x14matchStartToleranceM\x88\x01\x01\x126\n" +
	"\x15match_end_tolerance_m\x18\b \x01(\x01H\x05R\x12matchEndToleranceM\x88\x01\x01\x12)\n" +
	"\rbidirectional\x18\t \x01(\bH\x06R\rbidirectional\x88\x01\x01\x12\x1d\n" +
	"\astarred\x18\n" +
	" \x01(\bH\aR\astarred\x88\x01\x01\x12:\n" +
	"\bpolyline\x18\v \x01(\v2\x19.cairn.v1.EncodedPolylineH\bR\bpolyline\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\b\n" +
	"\x06_scopeB\x13\n" +
	"\x11_match_corridor_mB\x1a\n" +
	"\x18_match_start_tolerance_mB\x18\n" +
	"\x16_match_end_tolerance_mB\x10\n" +
	"\x0e_bidirectionalB\n" +
	"\n" +
	"\b_starredB\v\n" +
	"\t_polyline\"D\n" +
	"\x15UpdateSegmentResponse\x12+\n" +
	"\asegment\x18\x01 \x01(\v2\x11.cairn.v1.SegmentR\asegment\"I\n" +
	"\x14DeleteSegmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fkeep_efforts\x18\x02 \x01(\bR\vkeepEfforts\"\x17\n" +
	"\x15DeleteSegmentResponse\"\xe0\x01\n" +
	"\"SearchSegmentsInBoundingBoxRequest\x12)\n" +
	"\x04bbox\x18\x01 \x01(\v2\x15.cairn.v1.BoundingBoxR\x04bbox\x12=\n" +
	"\x0eactivity_types\x18\x02 \x03(\x0e2\x16.cairn.v1.ActivityTypeR\ractivityTypes\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12:\n" +
	"\x19include_instance_segments\x18\x04 \x01(\bR\x17includeInstanceSegments\"T\n" +
	"#SearchSegmentsInBoundingBoxResponse\x12-\n" +
	"\bsegments\x18\x01 \x03(\v2\x11.cairn.v1.SegmentR\bsegments\"\xf4\x01\n" +
	"\x19ListSegmentEffortsRequest\x12\x1d\n" +
	"\n" +
	"segment_id\x18\x01 \x01(\tR\tsegmentId\x122\n" +
	"\n" +
	"time_range\x18\x02 \x01(\v2\x13.cairn.v1.TimeRangeR\ttimeRange\x12\x1c\n" +
	"\auser_id\x18\x03 \x01(\tH\x00R\x06userId\x88\x01\x01\x12)\n" +
	"\x04page\x18\x04 \x01(\v2\x15.cairn.v1.PageRequestR\x04page\x12/\n" +
	"\x04sort\x18\x05 \x01(\x0e2\x1b.cairn.v1.SegmentEffortSortR\x04sortB\n" +
	"\n" +
	"\b_user_id\"{\n" +
	"\x1aListSegmentEffortsResponse\x121\n" +
	"\aefforts\x18\x01 \x03(\v2\x17.cairn.v1.SegmentEffortR\aefforts\x12*\n" +
	"\x04page\x18\x02 \x01(\v2\x16.cairn.v1.PageResponseR\x04page\"\x9b\x01\n" +
	"\x1bListMySegmentEffortsRequest\x12\x1d\n" +
	"\n" +
	"segment_id\x18\x01 \x01(\tR\tsegmentId\x122\n" +
	"\n" +
	"time_range\x18\x02 \x01(\v2\x13.cairn.v1.TimeRangeR\ttimeRange\x12)\n" +
	"\x04page\x18\x03 \x01(\v2\x15.cairn.v1.PageRequestR\x04page\"\xd8\x01\n" +
	"\x1cListMySegmentEffortsResponse\x121\n" +
	"\aefforts\x18\x01 \x03(\v2\x17.cairn.v1.SegmentEffortR\aefforts\x12*\n" +
	"\x04page\x18\x02 \x01(\v2\x16.cairn.v1.PageResponseR\x04page\x12E\n" +
	"\x0fpersonal_record\x18\x03 \x01(\v2\x17.cairn.v1.SegmentEffortH\x00R\x0epersonalRecord\x88\x01\x01B\x12\n" +
	"\x10_personal_record\"\xf4\x01\n" +
	"\x1cGetSegmentLeaderboardRequest\x12\x1d\n" +
	"\n" +
	"segment_id\x18\x01 \x01(\tR\tsegmentId\x122\n" +
	"\n" +
	"time_range\x18\x02 \x01(\v2\x13.cairn.v1.TimeRangeR\ttimeRange\x12C\n" +
	"\x0ebiological_sex\x18\x03 \x01(\x0e2\x17.cairn.v1.BiologicalSexH\x00R\rbiologicalSex\x88\x01\x01\x12)\n" +
	"\x04page\x18\x04 \x01(\v2\x15.cairn.v1.PageRequestR\x04pageB\x11\n" +
	"\x0f_biological_sex\"\xda\x02\n" +
	"\x10LeaderboardEntry\x12\x12\n" +
	"\x04rank\x18\x01 \x01(\x05R\x04rank\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12*\n" +
	"\x11user_display_name\x18\x03 \x01(\tR\x0fuserDisplayName\x12+\n" +
	"\x0fuser_avatar_url\x18\x04 \x01(\tH\x00R\ruserAvatarUrl\x88\x01\x01\x123\n" +
	"\aelapsed\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\aelapsed\x129\n" +
	"\n" +
	"start_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x12\x1b\n" +
	"\teffort_id\x18\a \x01(\tR\beffortId\x12\x1f\n" +
	"\vactivity_id\x18\b \x01(\tR\n" +
	"activityIdB\x12\n" +
	"\x10_user_avatar_url\"\xf4\x01\n" +
	"\x1dGetSegmentLeaderboardResponse\x124\n" +
	"\aentries\x18\x01 \x03(\v2\x1a.cairn.v1.LeaderboardEntryR\aentries\x12*\n" +
	"\x04page\x18\x02 \x01(\v2\x16.cairn.v1.PageResponseR\x04page\x12\x1c\n" +
	"\amy_rank\x18\x03 \x01(\x05H\x00R\x06myRank\x88\x01\x01\x12:\n" +
	"\bmy_entry\x18\x04 \x01(\v2\x1a.cairn.v1.LeaderboardEntryH\x01R\amyEntry\x88\x01\x01B\n" +
	"\n" +
	"\b_my_rankB\v\n" +
	"\t_my_entry\"Z\n" +
	"\x16RematchActivityRequest\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\tR\n" +
	"activityId\x12\x1f\n" +
	"\vsegment_ids\x18\x02 \x03(\tR\n" +
	"segmentIds\"0\n" +
	"\x17RematchActivityResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"j\n" +
	"\x15RematchSegmentRequest\x12\x1d\n" +
	"\n" +
	"segment_id\x18\x01 \x01(\tR\tsegmentId\x122\n" +
	"\n" +
	"time_range\x18\x02 \x01(\v2\x13.cairn.v1.TimeRangeR\ttimeRange\"/\n" +
	"\x16RematchSegmentResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId*d\n" +
	"\fSegmentScope\x12\x1d\n" +
	"\x19SEGMENT_SCOPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SEGMENT_SCOPE_PRIVATE\x10\x01\x12\x1a\n" +
	"\x16SEGMENT_SCOPE_INSTANCE\x10\x02*\xce\x01\n" +
	"\rClimbCategory\x12\x1e\n" +
	"\x1aCLIMB_CATEGORY_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13CLIMB_CATEGORY_NONE\x10\x01\x12\x17\n" +
	"\x13CLIMB_CATEGORY_FOUR\x10\x02\x12\x18\n" +
	"\x14CLIMB_CATEGORY_THREE\x10\x03\x12\x16\n" +
	"\x12CLIMB_CATEGORY_TWO\x10\x04\x12\x16\n" +
	"\x12CLIMB_CATEGORY_ONE\x10\x05\x12!\n" +
	"\x1dCLIMB_CATEGORY_HORS_CATEGORIE\x10\x06*\xcd\x01\n" +
	"\vSegmentSort\x12\x1c\n" +
	"\x18SEGMENT_SORT_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SEGMENT_SORT_NAME_ASC\x10\x01\x12\x1e\n" +
	"\x1aSEGMENT_SORT_DISTANCE_DESC\x10\x02\x12\x1f\n" +
	"\x1bSEGMENT_SORT_ELEVATION_DESC\x10\x03\x12\"\n" +
	"\x1eSEGMENT_SORT_EFFORT_COUNT_DESC\x10\x04\x12 \n" +
	"\x1cSEGMENT_SORT_CREATED_AT_DESC\x10\x05*\x86\x01\n" +
	"\x11SegmentEffortSort\x12#\n" +
	"\x1fSEGMENT_EFFORT_SORT_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fSEGMENT_EFFORT_SORT_ELAPSED_ASC\x10\x01\x12'\n" +
	"#SEGMENT_EFFORT_SORT_START_TIME_DESC\x10\x022\xf9\a\n" +
	"\x0eSegmentService\x12M\n" +
	"\fListSegments\x12\x1d.cairn.v1.ListSegmentsRequest\x1a\x1e.cairn.v1.ListSegmentsResponse\x12G\n" +
	"\n" +
	"GetSegment\x12\x1b.cairn.v1.GetSegmentRequest\x1a\x1c.cairn.v1.GetSegmentResponse\x12P\n" +
	"\rCreateSegment\x12\x1e.cairn.v1.CreateSegmentRequest\x1a\x1f.cairn.v1.CreateSegmentResponse\x12P\n" +
	"\rUpdateSegment\x12\x1e.cairn.v1.UpdateSegmentRequest\x1a\x1f.cairn.v1.UpdateSegmentResponse\x12P\n" +
	"\rDeleteSegment\x12\x1e.cairn.v1.DeleteSegmentRequest\x1a\x1f.cairn.v1.DeleteSegmentResponse\x12z\n" +
	"\x1bSearchSegmentsInBoundingBox\x12,.cairn.v1.SearchSegmentsInBoundingBoxRequest\x1a-.cairn.v1.SearchSegmentsInBoundingBoxResponse\x12_\n" +
	"\x12ListSegmentEfforts\x12#.cairn.v1.ListSegmentEffortsRequest\x1a$.cairn.v1.ListSegmentEffortsResponse\x12e\n" +
	"\x14ListMySegmentEfforts\x12%.cairn.v1.ListMySegmentEffortsRequest\x1a&.cairn.v1.ListMySegmentEffortsResponse\x12h\n" +
	"\x15GetSegmentLeaderboard\x12&.cairn.v1.GetSegmentLeaderboardRequest\x1a'.cairn.v1.GetSegmentLeaderboardResponse\x12V\n" +
	"\x0fRematchActivity\x12 .cairn.v1.RematchActivityRequest\x1a!.cairn.v1.RematchActivityResponse\x12S\n" +
	"\x0eRematchSegment\x12\x1f.cairn.v1.RematchSegmentRequest\x1a .cairn.v1.RematchSegmentResponseB\x9a\x01\n" +
	"\fcom.cairn.v1B\fSegmentProtoP\x01Z;github.com/johnnycube/cairn-core/gen/proto/cairn/v1;cairnv1\xa2\x02\x03CXX\xaa\x02\bCairn.V1\xca\x02\bCairn\\V1\xe2\x02\x14Cairn\\V1\\GPBMetadata\xea\x02\tCairn::V1b\x06proto3"

var (
	file_cairn_v1_segment_proto_rawDescOnce sync.Once
	file_cairn_v1_segment_proto_rawDescData []byte
)

func file_cairn_v1_segment_proto_rawDescGZIP() []byte {
	file_cairn_v1_segment_proto_rawDescOnce.Do(func() {
		file_cairn_v1_segment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cairn_v1_segment_proto_rawDesc), len(file_cairn_v1_segment_proto_rawDesc)))
	})
	return file_cairn_v1_segment_proto_rawDescData
}

var file_cairn_v1_segment_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_cairn_v1_segment_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_cairn_v1_segment_proto_goTypes = []any{
	(SegmentScope)(0),                           // 0: cairn.v1.SegmentScope
	(ClimbCategory)(0),                          // 1: cairn.v1.ClimbCategory
	(SegmentSort)(0),                            // 2: cairn.v1.SegmentSort
	(SegmentEffortSort)(0),                      // 3: cairn.v1.SegmentEffortSort
	(*Segment)(nil),                             // 4: cairn.v1.Segment
	(*SegmentStats)(nil),                        // 5: cairn.v1.SegmentStats
	(*SegmentEffort)(nil),                       // 6: cairn.v1.SegmentEffort
	(*ListSegmentsRequest)(nil),                 // 7: cairn.v1.ListSegmentsRequest
	(*ListSegmentsResponse)(nil),                // 8: cairn.v1.ListSegmentsResponse
	(*GetSegmentRequest)(nil),                   // 9: cairn.v1.GetSegmentRequest
	(*GetSegmentResponse)(nil),                  // 10: cairn.v1.GetSegmentResponse
	(*CreateSegmentRequest)(nil),                // 11: cairn.v1.CreateSegmentRequest
	(*CreateSegmentResponse)(nil),               // 12: cairn.v1.CreateSegmentResponse
	(*UpdateSegmentRequest)(nil),                // 13: cairn.v1.UpdateSegmentRequest
	(*UpdateSegmentResponse)(nil),               // 14: cairn.v1.UpdateSegmentResponse
	(*DeleteSegmentRequest)(nil),                // 15: cairn.v1.DeleteSegmentRequest
	(*DeleteSegmentResponse)(nil),               // 16: cairn.v1.DeleteSegmentResponse
	(*SearchSegmentsInBoundingBoxRequest)(nil),  // 17: cairn.v1.SearchSegmentsInBoundingBoxRequest
	(*SearchSegmentsInBoundingBoxResponse)(nil), // 18: cairn.v1.SearchSegmentsInBoundingBoxResponse
	(*ListSegmentEffortsRequest)(nil),           // 19: cairn.v1.ListSegmentEffortsRequest
	(*ListSegmentEffortsResponse)(nil),          // 20: cairn.v1.ListSegmentEffortsResponse
	(*ListMySegmentEffortsRequest)(nil),         // 21: cairn.v1.ListMySegmentEffortsRequest
	(*ListMySegmentEffortsResponse)(nil),        // 22: cairn.v1.ListMySegmentEffortsResponse
	(*GetSegmentLeaderboardRequest)(nil),        // 23: cairn.v1.GetSegmentLeaderboardRequest
	(*LeaderboardEntry)(nil),                    // 24: cairn.v1.LeaderboardEntry
	(*GetSegmentLeaderboardResponse)(nil),       // 25: cairn.v1.GetSegmentLeaderboardResponse
	(*RematchActivityRequest)(nil),              // 26: cairn.v1.RematchActivityRequest
	(*RematchActivityResponse)(nil),             // 27: cairn.v1.RematchActivityResponse
	(*RematchSegmentRequest)(nil),               // 28: cairn.v1.RematchSegmentRequest
	(*RematchSegmentResponse)(nil),              // 29: cairn.v1.RematchSegmentResponse
	(ActivityType)(0),                           // 30: cairn.v1.ActivityType
	(*EncodedPolyline)(nil),                     // 31: cairn.v1.EncodedPolyline
	(*BoundingBox)(nil),                         // 32: cairn.v1.BoundingBox
	(*timestamppb.Timestamp)(nil),               // 33: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),                 // 34: google.protobuf.Duration
	(*PageRequest)(nil),                         // 35: cairn.v1.PageRequest
	(*PageResponse)(nil),                        // 36: cairn.v1.PageResponse
	(*TimeRange)(nil),                           // 37: cairn.v1.TimeRange
	(BiologicalSex)(0),                          // 38: cairn.v1.BiologicalSex
}
var file_cairn_v1_segment_proto_depIdxs = []int32{
	0,  // 0: cairn.v1.Segment.scope:type_name -> cairn.v1.SegmentScope
	30, // 1: cairn.v1.Segment.activity_type:type_name -> cairn.v1.ActivityType
	31, // 2: cairn.v1.Segment.polyline:type_name -> cairn.v1.EncodedPolyline
	32, // 3: cairn.v1.Segment.bounding_box:type_name -> cairn.v1.BoundingBox
	1,  // 4: cairn.v1.Segment.climb_category:type_name -> cairn.v1.ClimbCategory
	5,  // 5: cairn.v1.Segment.stats:type_name -> cairn.v1.SegmentStats
	33, // 6: cairn.v1.Segment.created_at:type_name -> google.protobuf.Timestamp
	33, // 7: cairn.v1.Segment.updated_at:type_name -> google.protobuf.Timestamp
	34, // 8: cairn.v1.SegmentStats.kom_time:type_name -> google.protobuf.Duration
	34, // 9: cairn.v1.SegmentStats.pr_time:type_name -> google.protobuf.Duration
	33, // 10: cairn.v1.SegmentEffort.start_time:type_name -> google.protobuf.Timestamp
	34, // 11: cairn.v1.SegmentEffort.elapsed:type_name -> google.protobuf.Duration
	34, // 12: cairn.v1.SegmentEffort.moving:type_name -> google.protobuf.Duration
	33, // 13: cairn.v1.SegmentEffort.created_at:type_name -> google.protobuf.Timestamp
	0,  // 14: cairn.v1.ListSegmentsRequest.scopes:type_name -> cairn.v1.SegmentScope
	30, // 15: cairn.v1.ListSegmentsRequest.activity_types:type_name -> cairn.v1.ActivityType
	2,  // 16: cairn.v1.ListSegmentsRequest.sort:type_name -> cairn.v1.SegmentSort
	35, // 17: cairn.v1.ListSegmentsRequest.page:type_name -> cairn.v1.PageRequest
	4,  // 18: cairn.v1.ListSegmentsResponse.segments:type_name -> cairn.v1.Segment
	36, // 19: cairn.v1.ListSegmentsResponse.page:type_name -> cairn.v1.PageResponse
	4,  // 20: cairn.v1.GetSegmentResponse.segment:type_name -> cairn.v1.Segment
	6,  // 21: cairn.v1.GetSegmentResponse.top_efforts:type_name -> cairn.v1.SegmentEffort
	30, // 22: cairn.v1.CreateSegmentRequest.activity_type:type_name -> cairn.v1.ActivityType
	31, // 23: cairn.v1.CreateSegmentRequest.polyline:type_name -> cairn.v1.EncodedPolyline
	0,  // 24: cairn.v1.CreateSegmentRequest.scope:type_name -> cairn.v1.SegmentScope
	4,  // 25: cairn.v1.CreateSegmentResponse.segment:type_name -> cairn.v1.Segment
	0,  // 26: cairn.v1.UpdateSegmentRequest.scope:type_name -> cairn.v1.SegmentScope
	31, // 27: cairn.v1.UpdateSegmentRequest.polyline:type_name -> cairn.v1.EncodedPolyline
	4,  // 28: cairn.v1.UpdateSegmentResponse.segment:type_name -> cairn.v1.Segment
	32, // 29: cairn.v1.SearchSegmentsInBoundingBoxRequest.bbox:type_name -> cairn.v1.BoundingBox
	30, // 30: cairn.v1.SearchSegmentsInBoundingBoxRequest.activity_types:type_name -> cairn.v1.ActivityType
	4,  // 31: cairn.v1.SearchSegmentsInBoundingBoxResponse.segments:type_name -> cairn.v1.Segment
	37, // 32: cairn.v1.ListSegmentEffortsRequest.time_range:type_name -> cairn.v1.TimeRange
	35, // 33: cairn.v1.ListSegmentEffortsRequest.page:type_name -> cairn.v1.PageRequest
	3,  // 34: cairn.v1.ListSegmentEffortsRequest.sort:type_name -> cairn.v1.SegmentEffortSort
	6,  // 35: cairn.v1.ListSegmentEffortsResponse.efforts:type_name -> cairn.v1.SegmentEffort
	36, // 36: cairn.v1.ListSegmentEffortsResponse.page:type_name -> cairn.v1.PageResponse
	37, // 37: cairn.v1.ListMySegmentEffortsRequest.time_range:type_name -> cairn.v1.TimeRange
	35, // 38: cairn.v1.ListMySegmentEffortsRequest.page:type_name -> cairn.v1.PageRequest
	6,  // 39: cairn.v1.ListMySegmentEffortsResponse.efforts:type_name -> cairn.v1.SegmentEffort
	36, // 40: cairn.v1.ListMySegmentEffortsResponse.page:type_name -> cairn.v1.PageResponse
	6,  // 41: cairn.v1.ListMySegmentEffortsResponse.personal_record:type_name -> cairn.v1.SegmentEffort
	37, // 42: cairn.v1.GetSegmentLeaderboardRequest.time_range:type_name -> cairn.v1.TimeRange
	38, // 43: cairn.v1.GetSegmentLeaderboardRequest.biological_sex:type_name -> cairn.v1.BiologicalSex
	35, // 44: cairn.v1.GetSegmentLeaderboardRequest.page:type_name -> cairn.v1.PageRequest
	34, // 45: cairn.v1.LeaderboardEntry.elapsed:type_name -> google.protobuf.Duration
	33, // 46: cairn.v1.LeaderboardEntry.start_time:type_name -> google.protobuf.Timestamp
	24, // 47: cairn.v1.GetSegmentLeaderboardResponse.entries:type_name -> cairn.v1.LeaderboardEntry
	36, // 48: cairn.v1.GetSegmentLeaderboardResponse.page:type_name -> cairn.v1.PageResponse
	24, // 49: cairn.v1.GetSegmentLeaderboardResponse.my_entry:type_name -> cairn.v1.LeaderboardEntry
	37, // 50: cairn.v1.RematchSegmentRequest.time_range:type_name -> cairn.v1.TimeRange
	7,  // 51: cairn.v1.SegmentService.ListSegments:input_type -> cairn.v1.ListSegmentsRequest
	9,  // 52: cairn.v1.SegmentService.GetSegment:input_type -> cairn.v1.GetSegmentRequest
	11, // 53: cairn.v1.SegmentService.CreateSegment:input_type -> cairn.v1.CreateSegmentRequest
	13, // 54: cairn.v1.SegmentService.UpdateSegment:input_type -> cairn.v1.UpdateSegmentRequest
	15, // 55: cairn.v1.SegmentService.DeleteSegment:input_type -> cairn.v1.DeleteSegmentRequest
	17, // 56: cairn.v1.SegmentService.SearchSegmentsInBoundingBox:input_type -> cairn.v1.SearchSegmentsInBoundingBoxRequest
	19, // 57: cairn.v1.SegmentService.ListSegmentEfforts:input_type -> cairn.v1.ListSegmentEffortsRequest
	21, // 58: cairn.v1.SegmentService.ListMySegmentEfforts:input_type -> cairn.v1.ListMySegmentEffortsRequest
	23, // 59: cairn.v1.SegmentService.GetSegmentLeaderboard:input_type -> cairn.v1.GetSegmentLeaderboardRequest
	26, // 60: cairn.v1.SegmentService.RematchActivity:input_type -> cairn.v1.RematchActivityRequest
	28, // 61: cairn.v1.SegmentService.RematchSegment:input_type -> cairn.v1.RematchSegmentRequest
	8,  // 62: cairn.v1.SegmentService.ListSegments:output_type -> cairn.v1.ListSegmentsResponse
	10, // 63: cairn.v1.SegmentService.GetSegment:output_type -> cairn.v1.GetSegmentResponse
	12, // 64: cairn.v1.SegmentService.CreateSegment:output_type -> cairn.v1.CreateSegmentResponse
	14, // 65: cairn.v1.SegmentService.UpdateSegment:output_type -> cairn.v1.UpdateSegmentResponse
	16, // 66: cairn.v1.SegmentService.DeleteSegment:output_type -> cairn.v1.DeleteSegmentResponse
	18, // 67: cairn.v1.SegmentService.SearchSegmentsInBoundingBox:output_type -> cairn.v1.SearchSegmentsInBoundingBoxResponse
	20, // 68: cairn.v1.SegmentService.ListSegmentEfforts:output_type -> cairn.v1.ListSegmentEffortsResponse
	22, // 69: cairn.v1.SegmentService.ListMySegmentEfforts:output_type -> cairn.v1.ListMySegmentEffortsResponse
	25, // 70: cairn.v1.SegmentService.GetSegmentLeaderboard:output_type -> cairn.v1.GetSegmentLeaderboardResponse
	27, // 71: cairn.v1.SegmentService.RematchActivity:output_type -> cairn.v1.RematchActivityResponse
	29, // 72: cairn.v1.SegmentService.RematchSegment:output_type -> cairn.v1.RematchSegmentResponse
	62, // [62:73] is the sub-list for method output_type
	51, // [51:62] is the sub-list for method input_type
	51, // [51:51] is the sub-list for extension type_name
	51, // [51:51] is the sub-list for extension extendee
	0,  // [0:51] is the sub-list for field type_name
}

func init() { file_cairn_v1_segment_proto_init() }
func file_cairn_v1_segment_proto_init() {
	if File_cairn_v1_segment_proto != nil {
		return
	}
	file_cairn_v1_activity_proto_init()
	file_cairn_v1_common_proto_init()
	file_cairn_v1_metrics_proto_init()
	file_cairn_v1_segment_proto_msgTypes[0].OneofWrappers = []any{}
	file_cairn_v1_segment_proto_msgTypes[1].OneofWrappers = []any{}
	file_cairn_v1_segment_proto_msgTypes[2].OneofWrappers = []any{}
	file_cairn_v1_segment_proto_msgTypes[7].OneofWrappers = []any{}
	file_cairn_v1_segment_proto_msgTypes[8].OneofWrappers = []any{}
	file_cairn_v1_segment_proto_msgTypes[9].OneofWrappers = []any{}
	file_cairn_v1_segment_proto_msgTypes[15].OneofWrappers = []any{}
	file_cairn_v1_segment_proto_msgTypes[18].OneofWrappers = []any{}
	file_cairn_v1_segment_proto_msgTypes[19].OneofWrappers = []any{}
	file_cairn_v1_segment_proto_msgTypes[20].OneofWrappers = []any{}
	file_cairn_v1_segment_proto_msgTypes[21].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cairn_v1_segment_proto_rawDesc), len(file_cairn_v1_segment_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cairn_v1_segment_proto_goTypes,
		DependencyIndexes: file_cairn_v1_segment_proto_depIdxs,
		EnumInfos:         file_cairn_v1_segment_proto_enumTypes,
		MessageInfos:      file_cairn_v1_segment_proto_msgTypes,
	}.Build()
	File_cairn_v1_segment_proto = out.File
	file_cairn_v1_segment_proto_goTypes = nil
	file_cairn_v1_segment_proto_depIdxs = nil
}
